-- Generated by tools/build.py. Edit src/ instead.
local API = { Version = "2.0.0" }

-- Loader
do
-- Each API instance owns its configuration and module cache.
local settings = { Mode = "http", BaseUrl = "", LocalRoot = "FrostScripts" }
local cache, loading = {}, {}
local games = { GrassCutter = "games/GrassCutter/main.lua", NeedleInHay = "games/NeedleInHay/main.lua" }

function API.Configure(options)
	options = options or {}
	local mode = options.Mode or settings.Mode
	assert(mode == "http" or mode == "local", "Mode must be http or local")
	local base = options.BaseUrl or settings.BaseUrl
	local root = options.LocalRoot or settings.LocalRoot
	assert(type(base) == "string" and type(root) == "string", "Source paths must be strings")
	assert(mode ~= "http" or base:match("^https://"), "Set FrostScriptsConfig.BaseUrl to your HTTPS raw project URL")
	assert(next(loading) == nil, "Cannot change configuration while a module is loading")
	settings = { Mode = mode, BaseUrl = base:gsub("/+$", ""), LocalRoot = root:gsub("[/\\]+$", "") }
	table.clear(cache)
	return API
end

function API.GetConfig()
	return table.clone(settings)
end

function API.LoadModule(path, expectedMethod, fresh, ...)
	assert(type(path) == "string" and path:match("^[%w_/%-%.]+%.lua$")
		and not path:find("..", 1, true) and path:sub(1, 1) ~= "/", "Invalid module path")
	if not fresh and cache[path] ~= nil then return cache[path] end
	assert(not loading[path], "Circular module load: " .. path)
	assert(type(loadstring) == "function", "FrostScripts requires loadstring")
	loading[path] = true
	local args = table.pack(...)
	local ok, result = pcall(function()
		local source
		if settings.Mode == "local" then
			assert(type(readfile) == "function", "Local mode requires readfile")
			source = readfile(settings.LocalRoot .. "/" .. path)
		else
			assert(settings.BaseUrl:match("^https://"), "Configure an HTTPS BaseUrl before loading modules")
			source = game:HttpGet(settings.BaseUrl .. "/" .. path)
		end
		assert(type(source) == "string" and #source > 0, "Empty source for " .. path)
		local chunk, compileError = loadstring(source, "@FrostScripts/" .. path)
		assert(chunk, compileError)
		local value = chunk(table.unpack(args, 1, args.n))
		assert(type(value) == "table", path .. " must return a table")
		assert(not expectedMethod or type(value[expectedMethod]) == "function", path .. " has an incompatible interface")
		return value
	end)
	loading[path] = nil
	assert(ok, "FrostScripts could not load " .. path .. ": " .. tostring(result))
	if not fresh then cache[path] = result end
	return result
end

function API.LoadUI()
	-- Fresh UI factories isolate window theme state between game suites.
	return API.LoadModule("UI.lua", "new", true)
end

function API.RunGame(name)
	assert(games[name], "Unsupported game: " .. tostring(name) .. ". Choose GrassCutter or NeedleInHay.")
	return API.LoadModule(games[name], "Unload", true, API)
end

function API.GetGames()
	return { "GrassCutter", "NeedleInHay" }
end
end

-- Utilities
do
local Players = game:GetService("Players")

function API.GetCharacter(player)
	player = player or Players.LocalPlayer
	local character = player and player.Character
	return character,
		character and character:FindFirstChildOfClass("Humanoid"),
		character and character:FindFirstChild("HumanoidRootPart")
end

function API.GetPosition(object)
	if not object then return nil end
	if typeof(object) == "Vector3" then return object end
	if object:IsA("BasePart") then return object.Position end
	if object:IsA("Attachment") then return object.WorldPosition end
	if object:IsA("Model") then
		local ok, pivot = pcall(function() return object:GetPivot() end)
		if ok then return pivot.Position end
	end
	local part = object:FindFirstChildWhichIsA("BasePart", true)
	if part then return part.Position end
	local ancestor = object:FindFirstAncestorWhichIsA("BasePart") or object:FindFirstAncestorWhichIsA("Model")
	if ancestor then return API.GetPosition(ancestor) end
	return nil
end

function API.DistanceToPlayer(target, player)
	local _, _, root = API.GetCharacter(player)
	local position = API.GetPosition(target)
	return root and position and (root.Position - position).Magnitude or math.huge
end

function API.FormatNumber(value, compact)
	value = tonumber(value) or 0
	if value ~= value or math.abs(value) == math.huge then return "—" end
	if compact then
		for _, unit in ipairs({ { 1e15, "Q" }, { 1e12, "T" }, { 1e9, "B" }, { 1e6, "M" }, { 1e3, "K" } }) do
			if math.abs(value) >= unit[1] then
				local number = string.format("%.2f", value / unit[1]):gsub("0+$", ""):gsub("%.$", "")
				return number .. unit[2]
			end
		end
	end
	local sign = value < 0 and "-" or ""
	local digits = tostring(math.floor(math.abs(value) + 0.5))
	return sign .. (compact and digits or digits:reverse():gsub("(%d%d%d)", "%1,"):reverse():gsub("^,", ""))
end

function API.FormatDistance(value)
	if not value or value == math.huge then return "far" end
	return tostring(math.floor(value + 0.5)) .. " studs"
end

function API.CreateScope()
	local scope = { Closed = false, _items = {} }
	local function clean(item)
		if type(item) == "function" then item()
		elseif typeof(item) == "RBXScriptConnection" then item:Disconnect()
		elseif type(item.Destroy) == "function" then item:Destroy()
		elseif type(item.Disconnect) == "function" then item:Disconnect() end
	end
	function scope:Track(item)
		if item then
			if self.Closed then pcall(clean, item) else table.insert(self._items, item) end
		end
		return item
	end
	function scope:Destroy()
		if self.Closed then return end
		self.Closed = true
		for index = #self._items, 1, -1 do pcall(clean, self._items[index]) end
		table.clear(self._items)
	end
	return scope
end
end

-- Feature
do
local Feature = {}
Feature.__index = Feature
API.Feature = Feature

function API.CreateFeature(name, settings)
	return setmetatable({
		Name = name, Settings = settings or {}, Enabled = false, Status = "Ready",
		NextRun = 0, _token = 0, _connections = {},
	}, Feature)
end

function Feature:AddSetting(key, default)
	if self.Settings[key] == nil then self.Settings[key] = default end
	return self.Settings[key]
end

function Feature:SetSetting(key, value)
	assert(self.Settings[key] ~= nil, "Unknown " .. self.Name .. " setting: " .. tostring(key))
	self.Settings[key] = value
	if self.OnSettingChanged then self:OnSettingChanged(key, value) end
end

function Feature:_syncControl()
	local control = self._control
	if not control then return end
	if control.Toggle then control.Toggle:SetValue(self.Enabled, true) end
	control:SetEnabled(self.Enabled)
	control:SetStatus(self.Status)
end

function Feature:BindControl(control)
	self._control = control
	self:_syncControl()
	return self
end

function Feature:SetStatus(status)
	local value = tostring(status or "")
	if value == self.Status then return end
	self.Status = value
	self:_syncControl()
	if self.OnStatusChanged then self.OnStatusChanged(value) end
end

function Feature:Track(connection)
	if connection then table.insert(self._connections, connection) end
	return connection
end

function Feature:ClearConnections()
	for _, connection in ipairs(self._connections) do pcall(function() connection:Disconnect() end) end
	table.clear(self._connections)
end

function Feature:Enable()
	if self.Enabled then return true end
	self.Enabled = true
	self._token += 1
	local ok, result = pcall(function()
		if self.OnStateChanged then self.OnStateChanged(true) end
		if self.OnEnable then return self:OnEnable(self._token) end
	end)
	if not ok or result == false then
		self:Disable()
		self:SetStatus(ok and "Unable to start" or tostring(result))
		return false
	end
	self:_syncControl()
	return true
end

function Feature:Disable()
	if not self.Enabled then return end
	self.Enabled = false
	self._token += 1
	self:ClearConnections()
	local ok, err = pcall(function()
		if self.OnDisable then self:OnDisable() end
	end)
	local stateOK, stateError = pcall(function()
		if self.OnStateChanged then self.OnStateChanged(false) end
	end)
	if not ok or not stateOK then self.Status = tostring(not ok and err or stateError) end
	self:_syncControl()
end

function Feature:SetEnabled(enabled)
	if enabled then return self:Enable() end
	self:Disable()
	return true
end

function Feature:Destroy()
	self:Disable()
	self:ClearConnections()
	self._control = nil
end
end

-- Universal
do
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local VirtualInputManager
pcall(function() VirtualInputManager = game:GetService("VirtualInputManager") end)

API.UniversalModules = {}

function API.UniversalModules.CreateFlight(options)
	options = options or {}
	local feature = API.CreateFeature(options.Name or "Flight", {
		Speed = options.Speed or 70,
		ToggleKey = options.ToggleKey or Enum.KeyCode.F,
		VerticalSpeed = options.VerticalSpeed or 50,
		UpKey = options.UpKey or Enum.KeyCode.Space,
		DownKey = options.DownKey or Enum.KeyCode.LeftControl,
	})
	function feature:OnEnable()
		local player = Players.LocalPlayer
		local character = player.Character
		local humanoid = character and character:FindFirstChildOfClass("Humanoid")
		local root = character and character:FindFirstChild("HumanoidRootPart")
		if not humanoid or not root or humanoid.Health <= 0 then return false end
		self._humanoid = humanoid
		self._root = root
		self._previousAutoRotate = humanoid.AutoRotate
		self._previousPlatformStand = humanoid.PlatformStand
		humanoid.AutoRotate = false
		humanoid.PlatformStand = true
		local attachment = Instance.new("Attachment")
		attachment.Name = "FrostScriptsFlightAttachment"
		attachment.Parent = root
		local velocity = Instance.new("LinearVelocity")
		velocity.Name = "FrostScriptsFlightVelocity"
		velocity.Attachment0 = attachment
		velocity.RelativeTo = Enum.ActuatorRelativeTo.World
		velocity.VelocityConstraintMode = Enum.VelocityConstraintMode.Vector
		velocity.ForceLimitsEnabled = false
		velocity.VectorVelocity = Vector3.zero
		velocity.Parent = root
		local orientation = Instance.new("AlignOrientation")
		orientation.Name = "FrostScriptsFlightOrientation"
		orientation.Attachment0 = attachment
		orientation.Mode = Enum.OrientationAlignmentMode.OneAttachment
		orientation.MaxTorque = math.huge
		orientation.Responsiveness = 18
		orientation.Parent = root
		self._attachment = attachment
		self._velocity = velocity
		self._orientation = orientation
		self:Track(RunService.RenderStepped:Connect(function()
			if not root.Parent or not humanoid.Parent or humanoid.Health <= 0 then
				self:Disable()
				return
			end
			local camera = workspace.CurrentCamera
			local look = camera and camera.CFrame.LookVector or Vector3.new(0, 0, -1)
			local flatLook = Vector3.new(look.X, 0, look.Z)
			flatLook = flatLook.Magnitude > 0.001 and flatLook.Unit or Vector3.new(0, 0, -1)
			local flatRight = Vector3.new(-flatLook.Z, 0, flatLook.X)
			local move = Vector3.zero
			if UserInputService:GetFocusedTextBox() or (options.IsInputCaptured and options.IsInputCaptured()) then
				velocity.VectorVelocity = Vector3.zero
				return
			end
			if UserInputService:IsKeyDown(Enum.KeyCode.W) then move += flatLook end
			if UserInputService:IsKeyDown(Enum.KeyCode.S) then move -= flatLook end
			if UserInputService:IsKeyDown(Enum.KeyCode.D) then move += flatRight end
			if UserInputService:IsKeyDown(Enum.KeyCode.A) then move -= flatRight end
			if move.Magnitude > 1 then move = move.Unit end
			local vertical = 0
			if UserInputService:IsKeyDown(self.Settings.UpKey) then vertical += 1 end
			if UserInputService:IsKeyDown(self.Settings.DownKey) then vertical -= 1 end
			velocity.VectorVelocity = move * self.Settings.Speed + Vector3.new(0, vertical * self.Settings.VerticalSpeed, 0)
			orientation.CFrame = CFrame.lookAt(Vector3.zero, flatLook)
		end))
		self:SetStatus("WASD flight active")
		return true
	end
	function feature:OnDisable()
		if self._velocity then self._velocity:Destroy() end
		if self._orientation then self._orientation:Destroy() end
		if self._attachment then self._attachment:Destroy() end
		if self._humanoid and self._humanoid.Parent then
			self._humanoid.PlatformStand = self._previousPlatformStand
			self._humanoid.AutoRotate = self._previousAutoRotate
			self._humanoid:ChangeState(Enum.HumanoidStateType.GettingUp)
		end
		if self._root and self._root.Parent then
			self._root.AssemblyLinearVelocity = Vector3.zero
		end
		self._velocity, self._orientation, self._attachment = nil, nil, nil
		self._humanoid, self._root = nil, nil
		self:SetStatus("Flight disabled")
	end
	return feature
end

function API.UniversalModules.CreateAutoClicker(options)
	options = options or {}
	local feature = API.CreateFeature(options.Name or "Auto Clicker", {
		ClicksPerSecond = options.ClicksPerSecond or 8,
		ToggleKey = options.ToggleKey or Enum.KeyCode.V,
	})
	function feature:OnEnable(token)
		if not VirtualInputManager then
			self:SetStatus("VirtualInputManager unavailable")
			return false
		end
		task.spawn(function()
			while self.Enabled and self._token == token do
				local started = os.clock()
				if not UserInputService:GetFocusedTextBox()
					and not UserInputService:IsMouseButtonPressed(Enum.UserInputType.MouseButton1)
					and not (options.IsInputCaptured and options.IsInputCaptured()) then
					local ok, err = pcall(function()
						VirtualInputManager:SendMouseButtonEvent(0, 0, 0, true, game, 0)
						VirtualInputManager:SendMouseButtonEvent(0, 0, 0, false, game, 0)
					end)
					if not ok then
						self:Disable()
						self:SetStatus(tostring(err))
						break
					end
				end
				local rate = math.clamp(tonumber(self.Settings.ClicksPerSecond) or 8, 1, 30)
				task.wait(math.max(0.02, (1 / rate) - (os.clock() - started)))
			end
		end)
		self:SetStatus("Clicking")
		return true
	end
	function feature:OnDisable()
		self:SetStatus("Stopped")
	end
	return feature
end
end

return API
