-- Generated by tools/build.py. Edit src/ instead.
-- Generated entry points share this bootstrap. Configure once before running.
local env = (type(getgenv) == "function" and getgenv()) or _G
local config = env.FrostScriptsConfig or {}
config = table.clone(config)
config.BaseUrl = config.BaseUrl or "https://raw.githubusercontent.com/Fwrostt/FrostScripts/main"
assert(type(loadstring) == "function", "FrostScripts requires loadstring")
local mode = config.Mode or "http"
assert(mode == "local" or mode == "http", "FrostScripts Mode must be local or http")
local ok, source = pcall(function()
	if mode == "local" then
		assert(type(readfile) == "function", "Local mode requires readfile")
		return readfile((config.LocalRoot or "FrostScripts"):gsub("[/\\]+$", "") .. "/FrostScriptsAPI.lua")
	end
	assert(type(config.BaseUrl) == "string" and config.BaseUrl:match("^https://"),
		"Set getgenv().FrostScriptsConfig.BaseUrl to the HTTPS raw URL of your published project")
	return game:HttpGet(config.BaseUrl:gsub("/+$", "") .. "/FrostScriptsAPI.lua")
end)
assert(ok, "FrostScriptsAPI download failed: " .. tostring(source)
	.. ". Check the source URL and repository visibility, or use Mode = local with readfile.")
local chunk, compileError = loadstring(source, "@FrostScriptsAPI")
assert(chunk, compileError)
local API = chunk()
assert(type(API) == "table" and API.Version == "2.0.0" and type(API.Configure) == "function",
	"Incompatible FrostScriptsAPI; publish all files from the same build")
API.Configure(config)
return API.RunGame(config.Game or "")
