-- Generated by tools/build.py. Edit src/ instead.
local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local Library = {}
Library.__index = Library

local Window = {}
Window.__index = Window

local Tab = {}
Tab.__index = Tab

local Module = {}
Module.__index = Module

local THEMES = {
	Frost = {
		Background = Color3.fromRGB(10, 15, 24),
		Panel = Color3.fromRGB(13, 20, 31),
		PanelRaised = Color3.fromRGB(18, 27, 40),
		Surface = Color3.fromRGB(23, 34, 49),
		SurfaceHover = Color3.fromRGB(30, 44, 61),
		Border = Color3.fromRGB(44, 60, 78),
		Text = Color3.fromRGB(235, 243, 252),
		Muted = Color3.fromRGB(156, 175, 196),
		Accent = Color3.fromRGB(122, 213, 246),
		AccentHover = Color3.fromRGB(170, 230, 255),
		AccentSoft = Color3.fromRGB(24, 54, 70),
		Success = Color3.fromRGB(92, 196, 146),
		Danger = Color3.fromRGB(255, 185, 195),
		DangerSurface = Color3.fromRGB(51, 31, 36),
	},
	Neon = {
		Background = Color3.fromRGB(5, 8, 12),
		Panel = Color3.fromRGB(9, 13, 19),
		PanelRaised = Color3.fromRGB(13, 19, 27),
		Surface = Color3.fromRGB(17, 25, 36),
		SurfaceHover = Color3.fromRGB(23, 35, 49),
		Border = Color3.fromRGB(36, 56, 72),
		Text = Color3.fromRGB(234, 251, 255),
		Muted = Color3.fromRGB(134, 169, 180),
		Accent = Color3.fromRGB(0, 230, 255),
		AccentHover = Color3.fromRGB(75, 240, 255),
		AccentSoft = Color3.fromRGB(10, 49, 65),
		Success = Color3.fromRGB(55, 245, 144),
		Danger = Color3.fromRGB(255, 120, 144),
		DangerSurface = Color3.fromRGB(58, 22, 36),
	},
	Hayfield = {
		Background = Color3.fromRGB(12, 11, 8),
		Panel = Color3.fromRGB(19, 17, 12),
		PanelRaised = Color3.fromRGB(28, 24, 16),
		Surface = Color3.fromRGB(37, 31, 19),
		SurfaceHover = Color3.fromRGB(47, 39, 24),
		Border = Color3.fromRGB(73, 60, 34),
		Text = Color3.fromRGB(255, 246, 218),
		Muted = Color3.fromRGB(176, 158, 115),
		Accent = Color3.fromRGB(255, 196, 80),
		AccentHover = Color3.fromRGB(255, 213, 118),
		AccentSoft = Color3.fromRGB(66, 48, 19),
		Success = Color3.fromRGB(88, 214, 128),
		Danger = Color3.fromRGB(255, 159, 142),
		DangerSurface = Color3.fromRGB(67, 31, 26),
	},
	Rose = {
		Background = Color3.fromRGB(13, 8, 13),
		Panel = Color3.fromRGB(21, 12, 20),
		PanelRaised = Color3.fromRGB(29, 16, 28),
		Surface = Color3.fromRGB(39, 22, 38),
		SurfaceHover = Color3.fromRGB(51, 29, 49),
		Border = Color3.fromRGB(78, 45, 73),
		Text = Color3.fromRGB(255, 238, 248),
		Muted = Color3.fromRGB(183, 137, 166),
		Accent = Color3.fromRGB(255, 88, 177),
		AccentHover = Color3.fromRGB(255, 124, 197),
		AccentSoft = Color3.fromRGB(72, 24, 54),
		Success = Color3.fromRGB(111, 222, 151),
		Danger = Color3.fromRGB(255, 146, 146),
		DangerSurface = Color3.fromRGB(67, 28, 35),
	},
}

local function copyTheme(source)
	local result = {}
	for key, value in pairs(source) do
		result[key] = value
	end
	return result
end

local THEME = copyTheme(THEMES.Frost)

local SIZE_PRESETS = {
	Comfortable = Vector2.new(900, 580),
	Large = Vector2.new(1040, 650),
	["Extra Large"] = Vector2.new(1180, 720),
}

local CARD_HORIZONTAL_GUTTER = 8
local CARD_BODY_INSET = 16

local function create(className, properties, children)
	local object = Instance.new(className)
	if className == "TextLabel" or className == "TextButton" or className == "TextBox" then
		object.TextTruncate = Enum.TextTruncate.AtEnd
	end
	for property, value in pairs(properties or {}) do
		object[property] = value
		if typeof(value) == "Color3" then
			for themeKey, themeValue in pairs(THEME) do
				if value == themeValue then
					object:SetAttribute("FrostTheme_" .. property, themeKey)
					break
				end
			end
		end
	end
	for _, child in ipairs(children or {}) do
		child.Parent = object
	end
	if properties and properties.TextSize
		and (className == "TextLabel" or className == "TextButton" or className == "TextBox") then
		object:SetAttribute("FrostBaseTextSize", properties.TextSize)
	end
	return object
end

local function corner(radius)
	return create("UICorner", { CornerRadius = UDim.new(0, radius) })
end

local function stroke(color, transparency)
	return create("UIStroke", {
		Color = color or THEME.Border,
		Transparency = transparency or 0,
		Thickness = 1,
	})
end

local function safeCall(window, callback, ...)
	if not callback then return true end
	local ok, result = pcall(callback, ...)
	if not ok then
		window:Notify({
			Title = "Callback error",
			Text = tostring(result),
			Duration = 5,
			Type = "Error",
		})
	end
	return ok, result
end

local function optionParts(option)
	if type(option) == "table" then
		local value = option.Value
		if value == nil then value = option.value end
		if value == nil then value = option[2] end
		return tostring(option.Label or option.label or option.Name or option.name or option[1]), value
	end
	return tostring(option), option
end

local function copySelection(value)
	local result = {}
	if type(value) ~= "table" then return result end
	for key, selected in pairs(value) do
		if type(key) == "number" then
			result[selected] = true
		else
			result[key] = selected == true
		end
	end
	return result
end

function Window:_tween(object, duration, properties, style, direction)
	if self._destroyed then return nil end
	local running = self._tweens[object] or {}
	self._tweens[object] = running
	for property in pairs(properties) do
		if running[property] then running[property]:Cancel(); running[property] = nil end
	end
	for property, value in pairs(properties) do
		if typeof(value) == "Color3" then
			local key
			for name, color in pairs(THEME) do if color == value then key = name; break end end
			object:SetAttribute("FrostTheme_" .. property, key)
		end
	end
	if not self.Animations then
		for property, value in pairs(properties) do object[property] = value end
		return nil
	end
	local animation = TweenService:Create(
		object,
		TweenInfo.new(duration, style or Enum.EasingStyle.Quint, direction or Enum.EasingDirection.Out),
		properties
	)
	for property in pairs(properties) do running[property] = animation end
	animation:Play()
	return animation
end

function Window:_connect(signal, callback)
	local connection = signal:Connect(callback)
	table.insert(self._connections, connection)
	return connection
end

function Window:_hover(button, normalColor, hoverColor)
	local normalKey, hoverKey
	for key, color in pairs(THEME) do
		if color == normalColor then normalKey = key end
		if color == hoverColor then hoverKey = key end
	end
	self:_connect(button.MouseEnter, function()
		self:_tween(button, 0.14, { BackgroundColor3 = THEME[hoverKey] or hoverColor })
	end)
	self:_connect(button.MouseLeave, function()
		self:_tween(button, 0.14, { BackgroundColor3 = THEME[normalKey] or normalColor })
	end)
end

function Window:_makeDraggable(object, handle)
	local activeInput, dragStart, startCenter
	handle.Active = true
	self:_connect(handle.InputBegan, function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			activeInput, dragStart = input, input.Position
			startCenter = object.AbsolutePosition + object.AbsoluteSize / 2
		end
	end)
	self:_connect(UserInputService.InputEnded, function(input)
		if input == activeInput then activeInput = nil end
	end)
	self:_connect(UserInputService.InputChanged, function(input)
		if not activeInput or not self.Visible then return end
		if input ~= activeInput and input.UserInputType ~= Enum.UserInputType.MouseMovement then return end
		local delta = input.Position - dragStart
		local viewport = self.Gui.AbsoluteSize
		local half = object.AbsoluteSize / 2
		local center = startCenter + Vector2.new(delta.X, delta.Y)
		object.Position = UDim2.fromOffset(
			math.clamp(center.X, half.X, math.max(half.X, viewport.X - half.X)) + (object.AnchorPoint.X - 0.5) * object.AbsoluteSize.X,
			math.clamp(center.Y, half.Y, math.max(half.Y, viewport.Y - half.Y)) + (object.AnchorPoint.Y - 0.5) * object.AbsoluteSize.Y)
	end)
end

function Window:SetAnimations(enabled)
	self.Animations = enabled == true
	if not self.Animations then
		for object, running in pairs(self._tweens) do
			for _, animation in pairs(running) do animation:Cancel() end
			if object == self.Frame then object.GroupTransparency = self.Visible and 0 or 1 end
		end
		for _, tab in ipairs(self.Tabs) do
			for _, module in ipairs(tab.Modules) do module:_refreshHeight() end
		end
	end
end

-- Responsive geometry lives in Shell.lua.

-- Window resizing lives in Shell.lua.

function Window:SetSizePreset(preset)
	if not SIZE_PRESETS[preset] then return false end
	self.SizePreset = preset
	self:_resizeWindow(true)
	return true
end

function Window:_applyTextScale()
	local function apply(root)
		for _, descendant in ipairs(root:GetDescendants()) do
			local baseSize = descendant:GetAttribute("FrostBaseTextSize")
			if baseSize and (descendant:IsA("TextLabel") or descendant:IsA("TextButton") or descendant:IsA("TextBox")) then
				descendant.TextSize = math.max(11, math.floor(baseSize * self.TextScale + 0.5))
			end
		end
	end
	apply(self.Gui)
	apply(self.OverlayGui)
	apply(self.NotificationGui)
end

function Window:SetTextScale(scale)
	self.TextScale = math.clamp(tonumber(scale) or 1, 1, 1.3)
	self:_applyTextScale()
end

function Window:SetDimAmount(percent)
	self.DimAmount = math.clamp(tonumber(percent) or 48, 0, 75)
	self.Shade.BackgroundTransparency = 1 - (self.DimAmount / 100)
end

function Window:_layoutMonitors()
	local visible = {}
	for _, monitor in pairs(self.Monitors) do
		if monitor.Frame.Visible then table.insert(visible, monitor) end
	end
	table.sort(visible, function(a, b) return a.Order < b.Order end)
	for visibleIndex, monitor in ipairs(visible) do
		monitor.Frame.Size = UDim2.fromOffset(math.min(self.MonitorWidth, math.max(120, self.OverlayGui.AbsoluteSize.X - 44)), 64)
		monitor.Frame.AnchorPoint = self.MonitorSide == "Left" and Vector2.new(0, 0) or Vector2.new(1, 0)
		monitor.Frame.Position = self.MonitorSide == "Left"
			and UDim2.fromOffset(22, 22 + (visibleIndex - 1) * 74)
			or UDim2.new(1, -22, 0, 22 + (visibleIndex - 1) * 74)
	end
end

function Window:SetMonitorWidth(width)
	self.MonitorWidth = math.clamp(tonumber(width) or 380, 320, 520)
	self:_layoutMonitors()
end

function Window:SetMonitorSide(side)
	if side ~= "Left" and side ~= "Right" then return false end
	self.MonitorSide = side
	self:_layoutMonitors()
	return true
end

function Window:IsCapturingInput()
	return self._rebinding ~= nil or self._dropdown ~= nil or UserInputService:GetFocusedTextBox() ~= nil
end

function Window:GetRoot()
	return self.Gui
end

function Window:SetVisible(show)
	if self._destroyed then return end
	show = show == true
	if self.Visible == show then return end
	self:CloseDropdown()
	self._visibilityToken += 1
	local token = self._visibilityToken
	self.Visible = show
	self.Launcher.Visible = not show
	if show then
		self.Gui.Enabled = true
		self:_tween(self.Frame, 0.18, { GroupTransparency = 0 })
		self:_tween(self.Shade, 0.18, { BackgroundTransparency = 1 - self.DimAmount / 100 })
	else
		self.Search:ReleaseFocus()
		self:_tween(self.Frame, 0.14, { GroupTransparency = 1 })
		self:_tween(self.Shade, 0.14, { BackgroundTransparency = 1 })
		task.delay(self.Animations and 0.15 or 0, function()
			if not self._destroyed and token == self._visibilityToken then self.Gui.Enabled = false end
		end)
	end
end

function Window:Toggle()
	self:SetVisible(not self.Visible)
end

function Window:SelectTab(tab)
	if self._destroyed then return end
	if type(tab) == "string" then tab = self._tabsByName[tab] end
	if not tab or tab.Window ~= self then return end
	self:CloseDropdown()
	self.ActiveTab = tab
	for _, item in ipairs(self.Tabs) do
		local selected = item == tab
		item.Page.Visible = selected
		self:_tween(item.Button, 0.14, { BackgroundColor3 = selected and THEME.AccentSoft or THEME.Panel })
		self:_tween(item.Label, 0.14, { TextColor3 = selected and THEME.Text or THEME.Muted })
		self:_tween(item.IconLabel, 0.14, { TextColor3 = selected and THEME.Accent or THEME.Muted,
			BackgroundColor3 = selected and THEME.AccentSoft or THEME.Surface })
		item.Indicator.BackgroundTransparency = selected and 0 or 1
	end
	self.PageTitle.Text, self.PageSubtitle.Text = tab.Name, tab.Subtitle
	tab.Page.GroupTransparency = self.Animations and 0.3 or 0
	self:_tween(tab.Page, 0.16, { GroupTransparency = 0 })
	self:_refreshSearch()
end

function Window:AddTab(name, icon, subtitle)
	assert(not self._tabsByName[name], "Duplicate tab: " .. name)
	local tab = setmetatable({
		Window = self,
		Name = name,
		Icon = icon or "•",
		Subtitle = subtitle or "",
		Modules = {},
	}, Tab)
	tab.Page = create("CanvasGroup", {
		Name = name,
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		Visible = false,
		Parent = self.Content,
	})
	tab.Scroll = create("ScrollingFrame", {
		Name = name .. "List",
		Size = UDim2.fromScale(1, 1),
		Active = true,
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		CanvasSize = UDim2.new(),
		ScrollBarImageColor3 = THEME.Muted,
		ScrollBarImageTransparency = 0.35,
		ScrollBarThickness = 3,
		ScrollingDirection = Enum.ScrollingDirection.Y,
		Parent = tab.Page,
	}, {
		create("UIListLayout", {
			Padding = UDim.new(0, 14),
			SortOrder = Enum.SortOrder.LayoutOrder,
			HorizontalAlignment = Enum.HorizontalAlignment.Center,
		}),
		create("UIPadding", {
			PaddingBottom = UDim.new(0, 16),
		}),
	})
	local button = create("TextButton", {
		Name = name,
		Size = UDim2.new(1, 0, 0, 50),
		LayoutOrder = #self.Tabs + 1,
		AutoButtonColor = false,
		BackgroundColor3 = THEME.Panel,
		BorderSizePixel = 0,
		Text = "",
		Parent = self.Navigation,
	}, { corner(10) })
	local indicator = create("Frame", {
		Position = UDim2.fromOffset(4, 10),
		Size = UDim2.fromOffset(3, 30),
		BackgroundColor3 = THEME.Accent,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ZIndex = 4,
		Parent = button,
	}, { corner(3) })
	local iconLabel = create("TextLabel", {
		Position = UDim2.fromOffset(self._compact and 9 or 14, 10),
		Size = UDim2.fromOffset(28, 28),
		BackgroundColor3 = THEME.Surface,
		BorderSizePixel = 0,
		Text = tostring(tab.Icon),
		TextColor3 = THEME.Muted,
		Font = Enum.Font.GothamBold,
		TextSize = 12,
		Parent = button,
	}, { corner(8), stroke(THEME.Border, 0.55) })
	local label = create("TextLabel", {
		Position = UDim2.fromOffset(54, 0),
		Size = UDim2.new(1, -62, 1, 0),
		BackgroundTransparency = 1,
		Text = name,
		TextColor3 = THEME.Muted,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = button,
	})
	tab.Button, tab.Indicator, tab.IconLabel, tab.Label = button, indicator, iconLabel, label
	label.Visible = not self._compact
	table.insert(self.Tabs, tab)
	self._tabsByName[name] = tab
	self:_connect(button.MouseEnter, function()
		if self.ActiveTab ~= tab then
			self:_tween(button, 0.13, { BackgroundColor3 = THEME.PanelRaised })
		self:_tween(label, 0.13, { TextColor3 = THEME.Text })
			self:_tween(iconLabel, 0.13, { TextColor3 = THEME.Text, BackgroundColor3 = THEME.AccentSoft })
		end
	end)
	self:_connect(button.MouseLeave, function()
		if self.ActiveTab ~= tab then
			self:_tween(button, 0.13, { BackgroundColor3 = THEME.Panel })
			self:_tween(label, 0.13, { TextColor3 = THEME.Muted })
			self:_tween(iconLabel, 0.13, { TextColor3 = THEME.Muted, BackgroundColor3 = THEME.Surface })
		end
	end)
	self:_connect(button.Activated, function() self:SelectTab(tab) end)
	if #self.Tabs == 1 then self:SelectTab(tab) end
	return tab
end

function Module:_refreshHeight()
	if self.Window._destroyed then return end
	local bodyHeight = self.BodyLayout.AbsoluteContentSize.Y + 30
	self.Body.Size = UDim2.new(1, -(CARD_BODY_INSET * 2), 0, bodyHeight)
	local target = self.Expanded and self.HeaderHeight + bodyHeight or self.HeaderHeight
	self.Window:_tween(self.Card, 0.2, { Size = UDim2.new(1, -CARD_HORIZONTAL_GUTTER, 0, target) })
	self.Chevron.Text = self.Expanded and "⌃" or "⌄"
	self.Window:_queueTextScale()
end

function Module:SetExpanded(expanded)
	if self.Collapsible == false then expanded = true end
	self.Expanded = expanded == true
	self.Body.Visible = true
	self:_refreshHeight()
end

function Module:SetStatus(status)
	self.Status.Text = tostring(status or "")
end

function Module:SetEnabled(enabled)
	enabled = enabled == true
	local changed = self.Enabled ~= enabled
	self.Enabled = enabled
	if changed then self.Window:_refreshSearch() end
	self.Window:_tween(self.Status, 0.12, { TextColor3 = enabled and THEME.Success or THEME.Muted })
	self.Window:_tween(self.Accent, 0.14, {
		BackgroundColor3 = enabled and THEME.Accent or THEME.Border,
	})
end

function Window:_queueTextScale()
	if self._textScaleQueued or self._destroyed then return end
	self._textScaleQueued = true
	task.defer(function()
		self._textScaleQueued = false
		if not self._destroyed then self:_applyTextScale() end
	end)
end

function Module:_index(text)
	self.SearchText = self.SearchText .. " " .. tostring(text or ""):lower()
end

function Module:_row(height)
	local row = create("Frame", {
		Size = UDim2.new(1, 0, 0, height),
		BackgroundColor3 = THEME.Surface,
		BorderSizePixel = 0,
		Parent = self.Body,
	}, { corner(10) })
	task.defer(function() self:_refreshHeight() end)
	return row
end

function Module:AddToggle(name, default, callback, description)
	self:_index(name)
	local row = self:_row(description and 72 or 62)
	create("TextLabel", {
		Position = UDim2.fromOffset(16, description and 11 or 0),
		Size = UDim2.new(1, -96, 0, description and 22 or 62),
		BackgroundTransparency = 1,
		Text = name,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = row,
	})
	if description then
		create("TextLabel", {
			Position = UDim2.fromOffset(16, 37),
			Size = UDim2.new(1, -96, 0, 18),
			BackgroundTransparency = 1,
			Text = description,
			TextColor3 = THEME.Muted,
			TextXAlignment = Enum.TextXAlignment.Left,
			Font = Enum.Font.GothamMedium,
			TextSize = 12,
			Parent = row,
		})
	end
	local button = create("TextButton", {
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -18, 0.5, 0),
		Size = UDim2.fromOffset(48, 26),
		AutoButtonColor = false,
		BackgroundColor3 = THEME.Surface,
		BorderSizePixel = 0,
		Text = "",
		Parent = row,
	}, { corner(12), stroke(THEME.Border, 0.35) })
	local knob = create("Frame", {
		Position = UDim2.fromOffset(3, 3),
		Size = UDim2.fromOffset(20, 20),
		BackgroundColor3 = THEME.Text,
		BorderSizePixel = 0,
		Parent = button,
	}, { corner(9) })
	local control = { Value = default == true }
	function control:SetValue(value, silent)
		self.Value = value == true
		self.Module.Window:_tween(button, 0.14, {
			BackgroundColor3 = self.Value and THEME.Accent or THEME.PanelRaised,
		})
		self.Module.Window:_tween(knob, 0.14, {
			Position = self.Value and UDim2.fromOffset(25, 3) or UDim2.fromOffset(3, 3),
		})
		if not silent then safeCall(self.Module.Window, callback, self.Value) end
	end
	control.Module = self
	local hitTarget = create("TextButton", {
		AnchorPoint = Vector2.new(1, 0.5), Position = UDim2.new(1, -10, 0.5, 0),
		Size = UDim2.fromOffset(64, 44), Text = "", BackgroundTransparency = 1,
		ZIndex = 4, Parent = row,
	})
	self.Window:_connect(hitTarget.Activated, function()
		control:SetValue(not control.Value)
	end)
	control:SetValue(control.Value, true)
	return control
end

function Module:AddSlider(name, minimum, maximum, default, callback, options)
	self:_index(name)
	options = options or {}
	local row = self:_row(options.Description and 90 or 78)
	create("TextLabel", {
		Position = UDim2.fromOffset(16, 10),
		Size = UDim2.new(1, -104, 0, 22),
		BackgroundTransparency = 1,
		Text = name,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = row,
	})
	if options.Description then
		create("TextLabel", {
			Position = UDim2.fromOffset(16, 35),
			Size = UDim2.new(1, -104, 0, 18),
			BackgroundTransparency = 1,
			Text = options.Description,
			TextColor3 = THEME.Muted,
			TextXAlignment = Enum.TextXAlignment.Left,
			Font = Enum.Font.GothamMedium,
			TextSize = 12,
			Parent = row,
		})
	end
	local valueLabel = create("TextLabel", {
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -16, 0, 9),
		Size = UDim2.fromOffset(68, 26),
		BackgroundColor3 = THEME.PanelRaised,
		BorderSizePixel = 0,
		TextColor3 = THEME.Text,
		Font = Enum.Font.GothamBold,
		TextSize = 12,
		Parent = row,
	}, { corner(7), stroke(THEME.Border, 0.55) })
	local trackButton = create("TextButton", {
		Position = UDim2.new(0, 16, 1, -27),
		Size = UDim2.new(1, -32, 0, 18),
		AutoButtonColor = false,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Text = "",
		Parent = row,
	})
	local track = create("Frame", {
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.new(1, 0, 0, 6),
		BackgroundColor3 = THEME.PanelRaised,
		BorderSizePixel = 0,
		Parent = trackButton,
	}, { corner(4), stroke(THEME.Border, 0.5) })
	local fill = create("Frame", {
		Size = UDim2.fromScale(0, 1),
		BackgroundColor3 = THEME.Accent,
		BorderSizePixel = 0,
		Parent = track,
	}, { corner(4) })
	local knob = create("Frame", {
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.fromOffset(16, 16),
		BackgroundColor3 = THEME.Text,
		BorderSizePixel = 0,
		ZIndex = 3,
		Parent = track,
	}, { corner(8), stroke(THEME.Accent, 0.15) })
	local step = math.max(0.0001, tonumber(options.Step) or 1)
	assert(maximum >= minimum, "Slider maximum must be at least minimum")
	local formatter = options.Formatter
	local control = { Module = self, Value = default }
	local function display(value)
		if formatter then return tostring(formatter(value)) end
		if step >= 1 then return tostring(math.floor(value + 0.5)) end
		return string.format(step < 0.1 and "%.2f" or "%.1f", value)
	end
	function control:SetValue(value, silent)
		value = math.clamp(tonumber(value) or minimum, minimum, maximum)
		value = math.clamp(minimum + math.floor((value - minimum) / step + 0.5) * step, minimum, maximum)
		self.Value = value
		local alpha = maximum == minimum and 0 or (value - minimum) / (maximum - minimum)
		valueLabel.Text = display(value)
		fill.Size = UDim2.fromScale(alpha, 1)
		knob.Position = UDim2.fromScale(alpha, 0.5)
		if not silent then safeCall(self.Module.Window, callback, value) end
	end
	local dragging = false
	local function setFromPosition(x)
		if track.AbsoluteSize.X > 0 then
			control:SetValue(minimum + (maximum - minimum)
				* math.clamp((x - track.AbsolutePosition.X) / track.AbsoluteSize.X, 0, 1))
		end
	end
	self.Window:_connect(trackButton.InputBegan, function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			setFromPosition(input.Position.X)
			self.Window:_tween(knob, 0.1, { Size = UDim2.fromOffset(19, 19) })
		end
	end)
	self.Window:_connect(UserInputService.InputChanged, function(input)
		if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement
			or input.UserInputType == Enum.UserInputType.Touch) then
			setFromPosition(input.Position.X)
		end
	end)
	self.Window:_connect(UserInputService.InputEnded, function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch then
			dragging = false
			self.Window:_tween(knob, 0.1, { Size = UDim2.fromOffset(16, 16) })
		end
	end)
	control:SetValue(default, true)
	return control
end

function Module:AddDropdown(name, options, default, callback)
	self:_index(name)
	local row = self:_row(96)
	create("TextLabel", {
		Position = UDim2.fromOffset(16, 8),
		Size = UDim2.new(1, -32, 0, 24),
		BackgroundTransparency = 1,
		Text = name,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = row,
	})
	local button = create("TextButton", {
		AnchorPoint = Vector2.new(0, 0),
		Position = UDim2.fromOffset(12, 40),
		Size = UDim2.new(1, -24, 0, 44),
		AutoButtonColor = false,
		BackgroundColor3 = THEME.PanelRaised,
		BorderSizePixel = 0,
		TextColor3 = THEME.Text,
		Font = Enum.Font.GothamBold,
		TextSize = 13,
		Parent = row,
	}, { corner(8), stroke(THEME.Border, 0.45) })
	self.Window:_hover(button, THEME.PanelRaised, THEME.SurfaceHover)
	local control = { Module = self, Value = default, Index = 1 }
	for index, option in ipairs(options) do
		local _, value = optionParts(option)
		if value == default then
			control.Index = index
			break
		end
	end
	function control:SetValue(value, silent)
		for index, option in ipairs(options) do
			local label, candidate = optionParts(option)
			if candidate == value then
				self.Index, self.Value = index, candidate
				button.Text = label .. "   ▾"
				if not silent then safeCall(self.Module.Window, callback, candidate) end
				return
			end
		end
	end
	self.Window:_connect(button.Activated, function()
		if #options > 0 then self.Window:_openDropdown(control, name, options, button) end
	end)
	if #options > 0 then
		local _, initial = optionParts(options[control.Index])
		control:SetValue(initial, true)
	else button.Text = "No options" end
	return control
end

function Module:AddMultiDropdown(name, options, defaults, callback, colors)
	self:_index(name)
	local rows = math.ceil(#options / 3)
	local row = self:_row(48 + rows * 46)
	create("TextLabel", {
		Position = UDim2.fromOffset(16, 10),
		Size = UDim2.new(1, -28, 0, 20),
		BackgroundTransparency = 1,
		Text = name,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = row,
	})
	local control = { Module = self, Value = copySelection(defaults), Buttons = {} }
	function control:_refresh(option)
		local button = self.Buttons[option]
		if button then
			self.Module.Window:_tween(button, 0.12, {
				BackgroundColor3 = self.Value[option] and THEME.AccentSoft or THEME.PanelRaised,
				TextColor3 = self.Value[option] and ((colors and colors[option]) or THEME.Text) or THEME.Muted,
			})
			button.Text = (self.Value[option] and "✓ " or "") .. tostring(option)
		end
	end
	function control:SetValue(values, silent)
		self.Value = copySelection(values)
		for _, option in ipairs(options) do self:_refresh(option) end
		if not silent then safeCall(self.Module.Window, callback, copySelection(self.Value)) end
	end
	for index, option in ipairs(options) do
		local column, line = (index - 1) % 3, math.floor((index - 1) / 3)
		local button = create("TextButton", {
			Position = UDim2.new(column / 3, 8 + column * 2, 0, 40 + line * 46),
			Size = UDim2.new(1 / 3, -13, 0, 42),
			AutoButtonColor = false,
			BorderSizePixel = 0,
			Text = option,
			Font = Enum.Font.GothamBold,
			TextSize = 12,
			Parent = row,
		}, { corner(7) })
		control.Buttons[option] = button
		self.Window:_connect(button.Activated, function()
			control.Value[option] = not control.Value[option]
			control:_refresh(option)
			safeCall(self.Window, callback, copySelection(control.Value))
		end)
	end
	control:SetValue(defaults, true)
	return control
end

function Module:AddNumberInput(name, default, callback, options)
	self:_index(name)
	options = options or {}
	local row = self:_row(96)
	create("TextLabel", {
		Position = UDim2.fromOffset(16, 8),
		Size = UDim2.new(1, -32, 0, 24),
		BackgroundTransparency = 1,
		Text = name,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = row,
	})
	local box = create("TextBox", {
		Position = UDim2.fromOffset(12, 40),
		Size = UDim2.new(1, -24, 0, 44),
		BackgroundColor3 = THEME.PanelRaised,
		BorderSizePixel = 0,
		ClearTextOnFocus = false,
		Text = tostring(default),
		TextColor3 = THEME.Text,
		PlaceholderColor3 = THEME.Muted,
		Font = Enum.Font.GothamBold,
		TextSize = 13,
		Parent = row,
	}, { corner(8), stroke(THEME.Border, 0.45) })
	local control = { Module = self, Value = tonumber(default) or 0 }
	function control:SetValue(value, silent)
		value = tonumber(value) or self.Value
		if value ~= value or math.abs(value) == math.huge then value = self.Value end
		if options.Min then value = math.max(options.Min, value) end
		if options.Max then value = math.min(options.Max, value) end
		self.Value = value
		box.Text = tostring(value)
		if not silent then safeCall(self.Module.Window, callback, value) end
	end
	self.Window:_connect(box.FocusLost, function() control:SetValue(box.Text) end)
	return control
end

function Module:AddButton(name, callback, options)
	self:_index(name)
	options = options or {}
	local row = self:_row(54)
	local danger = options.Danger == true
	local button = create("TextButton", {
		Size = UDim2.fromScale(1, 1),
		AutoButtonColor = false,
		BackgroundColor3 = danger and THEME.DangerSurface or THEME.AccentSoft,
		BorderSizePixel = 0,
		Text = name,
		TextColor3 = danger and THEME.Danger or THEME.Text,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = row,
	}, { corner(10), stroke(danger and THEME.Danger or THEME.Accent, 0.35) })
	self.Window:_hover(
		button,
		danger and THEME.DangerSurface or THEME.AccentSoft,
		danger and THEME.DangerSurface or THEME.SurfaceHover
	)
	self.Window:_connect(button.Activated, function() safeCall(self.Window, callback) end)
	return button
end

function Module:AddParagraph(title, text, options)
	self:_index(title)
	self:_index(text)
	options = options or {}
	local row = self:_row(options.Height or 88)
	create("TextLabel", {
		Position = UDim2.fromOffset(16, 12),
		Size = UDim2.new(1, -28, 0, 20),
		BackgroundTransparency = 1,
		Text = title,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = row,
	})
	local label = create("TextLabel", {
		Position = UDim2.fromOffset(16, 38),
		Size = UDim2.new(1, -32, 1, -48),
		BackgroundTransparency = 1,
		Text = text,
		TextColor3 = THEME.Muted,
		TextWrapped = true,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		Font = Enum.Font.GothamMedium,
		TextSize = 12,
		Parent = row,
	})
	return {
		SetText = function(_, value) label.Text = tostring(value) end,
		SetColor = function(_, color) label.TextColor3 = color end,
	}
end

function Tab:AddModule(options)
	if type(options) == "string" then options = { Name = options } end
	options = options or {}
	local module = setmetatable({
		Window = self.Window,
		Tab = self,
		Name = options.Name or "Module",
		SearchText = ((options.Name or "Module") .. " " .. (options.Description or "")):lower(),
		HeaderHeight = options.HeaderHeight or 68,
		Expanded = options.Expanded == true or options.Collapsible == false,
		Collapsible = options.Collapsible ~= false,
		Enabled = false,
	}, Module)
	module.Card = create("Frame", {
		Name = module.Name,
		Size = UDim2.new(1, -CARD_HORIZONTAL_GUTTER, 0, module.HeaderHeight),
		BackgroundColor3 = THEME.PanelRaised,
		BorderSizePixel = 0,
		ClipsDescendants = true,
		LayoutOrder = #self.Modules + 1,
		Parent = self.Scroll,
	}, { corner(13), stroke(THEME.Border, 0.25) })
	module.Accent = create("Frame", {
		Position = UDim2.fromOffset(4, 12),
		Size = UDim2.fromOffset(3, math.max(24, module.HeaderHeight - 24)),
		BackgroundColor3 = options.Accent and THEME.Accent or THEME.Border,
		BorderSizePixel = 0,
		ZIndex = 3,
		Parent = module.Card,
	}, { corner(3) })
	create("TextLabel", {
		Position = UDim2.fromOffset(24, 12),
		Size = UDim2.new(1, -(options.RightInset or (options.Toggleable and 148 or 58)), 0, 22),
		BackgroundTransparency = 1,
		Text = module.Name,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = options.TitleSize or 16,
		Parent = module.Card,
	})
	module.Status = create("TextLabel", {
		Position = UDim2.fromOffset(24, 38),
		Size = UDim2.new(1, -(options.RightInset or (options.Toggleable and 148 or 64)), 0, 20),
		BackgroundTransparency = 1,
		Text = options.Description or options.Status or "Ready",
		TextColor3 = THEME.Muted,
		TextTruncate = Enum.TextTruncate.AtEnd,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamMedium,
		TextSize = 12,
		Parent = module.Card,
	})
	module.Chevron = create("TextLabel", {
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, options.Toggleable and -88 or -19, 0, 20),
		Size = UDim2.fromOffset(18, 24),
		BackgroundTransparency = 1,
		Text = module.Expanded and "⌃" or "⌄",
		TextColor3 = THEME.Muted,
		Font = Enum.Font.GothamBold,
		TextSize = 15,
		Visible = module.Collapsible,
		Parent = module.Card,
	})
	local headerButton = create("TextButton", {
		Size = UDim2.new(1, options.Toggleable and -78 or 0, 0, module.HeaderHeight),
		AutoButtonColor = false,
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Text = "",
		ZIndex = 2,
		Parent = module.Card,
	})
	module.Body = create("Frame", {
		Position = UDim2.fromOffset(CARD_BODY_INSET, module.HeaderHeight),
		Size = UDim2.new(1, -(CARD_BODY_INSET * 2), 0, 0),
		BackgroundTransparency = 1,
		Parent = module.Card,
	})
	module.BodyLayout = create("UIListLayout", {
		Padding = UDim.new(0, 10),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = module.Body,
	})
	self.Window:_connect(module.BodyLayout:GetPropertyChangedSignal("AbsoluteContentSize"), function()
		module:_refreshHeight()
	end)
	if module.Collapsible then
		self.Window:_connect(headerButton.Activated, function()
			module:SetExpanded(not module.Expanded)
		end)
		self.Window:_connect(headerButton.MouseEnter, function()
			self.Window:_tween(module.Card, 0.14, { BackgroundColor3 = THEME.Surface })
		end)
		self.Window:_connect(headerButton.MouseLeave, function()
			self.Window:_tween(module.Card, 0.14, { BackgroundColor3 = THEME.PanelRaised })
		end)
	end
	if options.Toggleable then
		module.Toggle = module:AddToggle("", options.Default == true, options.Callback)
		local toggleRow = module.Toggle
		for _, child in ipairs(module.Body:GetChildren()) do
			if child:IsA("Frame") then
				child.Visible = false
				child.Size = UDim2.new(1, 0, 0, 0)
				break
			end
		end
		local toggleButton = create("TextButton", {
			AnchorPoint = Vector2.new(1, 0),
			Position = UDim2.new(1, -22, 0, 18),
			Size = UDim2.fromOffset(48, 26),
			AutoButtonColor = false,
			BackgroundColor3 = THEME.Surface,
			BorderSizePixel = 0,
			Text = "",
			ZIndex = 5,
			Parent = module.Card,
		}, { corner(12) })
		local knob = create("Frame", {
			Position = UDim2.fromOffset(3, 3),
			Size = UDim2.fromOffset(20, 20),
			BackgroundColor3 = THEME.Text,
			BorderSizePixel = 0,
			ZIndex = 6,
			Parent = toggleButton,
		}, { corner(9) })
		function toggleRow:SetValue(value, silent)
			self.Value = value == true
			self.Module.Window:_tween(toggleButton, 0.14, {
				BackgroundColor3 = self.Value and THEME.Accent or THEME.Surface,
			})
			self.Module.Window:_tween(knob, 0.14, {
				Position = self.Value and UDim2.fromOffset(25, 3) or UDim2.fromOffset(3, 3),
			})
			self.Module:SetEnabled(self.Value)
			if not silent then safeCall(self.Module.Window, options.Callback, self.Value) end
		end
		local hitTarget = create("TextButton", {
			AnchorPoint = Vector2.new(1, 0), Position = UDim2.new(1, -14, 0, 9),
			Size = UDim2.fromOffset(64, 44), Text = "", BackgroundTransparency = 1,
			ZIndex = 7, Parent = module.Card,
		})
		self.Window:_connect(hitTarget.Activated, function()
			toggleRow:SetValue(not toggleRow.Value)
		end)
		toggleRow:SetValue(options.Default == true, true)
	end
	if options.Feature then options.Feature:BindControl(module) end

	module:SetExpanded(module.Expanded)
	table.insert(self.Modules, module)
	self.Window:_refreshSearch()
	return module
end

function Tab:AddKeybind(options)
	options = options or {}
	local module = self:AddModule({
		Name = options.Name or "Keybind",
		Description = options.Description or "Click to rebind",
		Collapsible = false,
		HeaderHeight = 76,
		RightInset = 184,
	})
	module.Body.Visible = false
	module.Card.Size = UDim2.new(1, -CARD_HORIZONTAL_GUTTER, 0, 76)
	local button = create("TextButton", {
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -22, 0.5, 0),
		Size = UDim2.fromOffset(132, 42),
		AutoButtonColor = false,
		BackgroundColor3 = THEME.Surface,
		BorderSizePixel = 0,
		TextColor3 = THEME.Text,
		Font = Enum.Font.GothamBold,
		TextSize = 13,
		ZIndex = 4,
		Parent = module.Card,
	}, { corner(9), stroke(THEME.Border, 0.25) })
	local binding = {
		Window = self.Window,
		Button = button,
		Name = options.Name or "Keybind",
		Get = options.Get,
		Set = options.Set,
		OnPressed = options.OnPressed,
		AllowClear = options.AllowClear ~= false,
	}
	function binding:Refresh()
		local key = self.Get()
		self.Button.Text = key == Enum.KeyCode.Unknown and "None" or key.Name
		self.Button.TextColor3 = THEME.Text
	end
	self.Window:_hover(button, THEME.Surface, THEME.SurfaceHover)
	self.Window:_connect(button.Activated, function()
		if self.Window._rebinding then self.Window._rebinding:Refresh() end
		self.Window._rebinding = binding
		button.Text = "Press a key..."
		button.TextColor3 = THEME.Accent
	end)
	table.insert(self.Window.Keybinds, binding)
	binding:Refresh()
	return binding
end

function Window:_keyInUse(key, except)
	for _, binding in ipairs(self.Keybinds) do
		if binding ~= except and binding.Get() == key then return binding.Name end
	end
	return nil
end

function Window:_handleKeyboard(input, processed)
	if input.UserInputType ~= Enum.UserInputType.Keyboard then return end
	if self._rebinding then
		local binding = self._rebinding
		local key = input.KeyCode
		if key == Enum.KeyCode.Escape then
			binding:Refresh()
		elseif (key == Enum.KeyCode.Backspace or key == Enum.KeyCode.Delete) and binding.AllowClear then
			binding.Set(Enum.KeyCode.Unknown)
			binding:Refresh()
		elseif self.ReservedKeys[key] then
			binding:Refresh()
			self:Notify({ Title = "Reserved key", Text = key.Name .. " is used for movement.", Type = "Error" })
		else
			local conflict = self:_keyInUse(key, binding)
			if conflict then
				binding:Refresh()
				self:Notify({ Title = "Key already assigned", Text = key.Name .. " is bound to " .. conflict .. ".", Type = "Error" })
			else
				binding.Set(key)
				binding:Refresh()
			end
		end
		self._rebinding = nil
		return
	end
	if self._dropdown and input.KeyCode == Enum.KeyCode.Escape then self:CloseDropdown(); return end
	if input.KeyCode == Enum.KeyCode.K and (UserInputService:IsKeyDown(Enum.KeyCode.LeftControl)
		or UserInputService:IsKeyDown(Enum.KeyCode.RightControl)) and not processed then
		self:SetVisible(true)
		self.Search:CaptureFocus()
		return
	end
	if UserInputService:GetFocusedTextBox() == self.Search and input.KeyCode == Enum.KeyCode.Escape then
		self:SetSearch(""); self.Search:ReleaseFocus(); return
	end
	if self._dropdown or processed or UserInputService:GetFocusedTextBox() then return end
	for _, binding in ipairs(self.Keybinds) do
		local key = binding.Get()
		if key ~= Enum.KeyCode.Unknown and input.KeyCode == key then
			safeCall(self, binding.OnPressed)
			break
		end
	end
end

function Window:SetMonitor(key, text)
	local nextText = text ~= nil and tostring(text) or nil
	local monitor = self.Monitors[key]
	local wasVisible = monitor and monitor.Frame.Visible
	if not monitor then
		self._monitorCount += 1
		local frame = create("Frame", {
			AnchorPoint = Vector2.new(1, 0),
			Position = UDim2.new(1, -22, 0, 22 + ((self._monitorCount - 1) * 74)),
			Size = UDim2.fromOffset(self.MonitorWidth, 64),
			BackgroundColor3 = THEME.PanelRaised,
			BackgroundTransparency = 0.04,
			BorderSizePixel = 0,
			ClipsDescendants = true,
			Parent = self.OverlayGui,
		}, { corner(10), stroke(THEME.Border, 0.25) })
		create("Frame", {
			Position = UDim2.fromOffset(0, 10),
			Size = UDim2.fromOffset(4, 44),
			BackgroundColor3 = THEME.Accent,
			BorderSizePixel = 0,
			Parent = frame,
		}, { corner(3) })
		local label = create("TextLabel", {
			Position = UDim2.fromOffset(18, 8),
			Size = UDim2.new(1, -34, 1, -16),
			BackgroundTransparency = 1,
			TextColor3 = THEME.Text,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextYAlignment = Enum.TextYAlignment.Center,
			TextWrapped = true,
			Font = Enum.Font.GothamBold,
			TextSize = 13,
			Parent = frame,
		})
		self:_makeDraggable(frame, frame)
		monitor = { Frame = frame, Label = label, Order = self._monitorCount }
		self.Monitors[key] = monitor
	end
	if monitor.Text == nextText and monitor.Frame.Visible == (nextText ~= nil) then
		return monitor
	end
	monitor.Text = nextText
	monitor.Label.Text = nextText or ""
	monitor.Frame.Visible = nextText ~= nil
	if not wasVisible and nextText ~= nil then self:_layoutMonitors() end
	self:_applyTextScale()
	return monitor
end

function Window:HideMonitor(key)
	if self.Monitors[key] then
		self.Monitors[key].Frame.Visible = false
		self:_layoutMonitors()
	end
end

function Window:_layoutNotifications()
	local size = self.OverlayGui.AbsoluteSize
	local maxVisible = math.max(1, math.min(3, math.floor((size.Y - 32) / 108)))
	for index = #self.Notifications, 1, -1 do
		if not self.Notifications[index].Parent then table.remove(self.Notifications, index) end
	end
	while #self.Notifications > maxVisible do table.remove(self.Notifications, 1):Destroy() end
	for index, frame in ipairs(self.Notifications) do
		frame.Size = UDim2.fromOffset(math.min(380, math.max(120, size.X - 32)), 96)
		frame.Position = UDim2.new(1, -16, 1, -16 - (#self.Notifications - index) * 108)
	end
end

function Window:Notify(options)
	if self._destroyed then return nil end
	if type(options) == "string" then options = { Text = options } end
	options = options or {}
	local duration = math.clamp(tonumber(options.Duration) or 4, 1, 30)
	local tint = options.Type == "Error" and THEME.Danger or options.Type == "Success" and THEME.Success or THEME.Accent
	local frame = create("CanvasGroup", {
		Name = "Notification", AnchorPoint = Vector2.new(1, 1), Size = UDim2.fromOffset(380, 96),
		BackgroundColor3 = THEME.PanelRaised, BorderSizePixel = 0, GroupTransparency = 1,
		Parent = self.NotificationGui,
	}, { corner(12), stroke(tint, 0.6) })
	create("Frame", { Position = UDim2.fromOffset(0, 16), Size = UDim2.new(0, 3, 1, -32),
		BackgroundColor3 = tint, BorderSizePixel = 0, Parent = frame }, { corner(2) })
	create("TextLabel", { Position = UDim2.fromOffset(16, 12), Size = UDim2.new(1, -66, 0, 22),
		Text = options.Title or "FrostScripts", TextColor3 = tint, BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left, TextSize = 14, Font = Enum.Font.GothamBold, Parent = frame })
	create("TextLabel", { Position = UDim2.fromOffset(16, 38), Size = UDim2.new(1, -32, 0, 44),
		Text = options.Text or "", TextColor3 = THEME.Text, BackgroundTransparency = 1, TextWrapped = true,
		TextXAlignment = Enum.TextXAlignment.Left, TextYAlignment = Enum.TextYAlignment.Top,
		TextSize = 12, Font = Enum.Font.GothamMedium, Parent = frame })
	local close = create("TextButton", { Position = UDim2.new(1, -44, 0, 0), Size = UDim2.fromOffset(44, 44),
		Text = "×", TextColor3 = THEME.Muted, TextSize = 20, Font = Enum.Font.Gotham,
		BackgroundTransparency = 1, Parent = frame })
	local progress = create("Frame", { Position = UDim2.new(0, 0, 1, -2), Size = UDim2.new(1, 0, 0, 2),
		BackgroundColor3 = tint, BorderSizePixel = 0, Parent = frame })
	local closeConnection
	closeConnection = close.Activated:Connect(function()
		closeConnection:Disconnect()
		frame:Destroy()
		if not self._destroyed then self:_layoutNotifications() end
	end)
	table.insert(self.Notifications, frame)
	self:_layoutNotifications()
	self:_queueTextScale()
	self:_tween(frame, 0.18, { GroupTransparency = 0 })
	if self.Animations then self:_tween(progress, duration, { Size = UDim2.new(0, 0, 0, 2) }, Enum.EasingStyle.Linear) end
	task.delay(duration, function()
		closeConnection:Disconnect()
		if self._destroyed or not frame.Parent then return end
		self:_tween(frame, 0.14, { GroupTransparency = 1 })
		task.delay(self.Animations and 0.15 or 0, function()
			frame:Destroy()
			if not self._destroyed then self:_layoutNotifications() end
		end)
	end)
	return frame
end


function Window:AddWorldMarker(instances, object, options)
	options = options or {}
	instances = instances or {}
	local color = options.Color or THEME.Accent
	local adornment = object:IsA("Model") and object or object:FindFirstAncestorWhichIsA("Model") or object
	local part = options.Adornee
	if not (typeof(part) == "Instance" and part:IsA("BasePart")) then
		part = adornment:IsA("BasePart") and adornment or adornment:FindFirstChildWhichIsA("BasePart", true)
	end
	if not part then return end
	local highlight
	if options.Highlight ~= false then
		highlight = Instance.new("Highlight")
		highlight.Name = "FrostScriptsMarker"
		highlight.Adornee = adornment
		highlight.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop
		highlight.FillColor = color
		highlight.FillTransparency = 0.8
		highlight.OutlineColor = color
		highlight.OutlineTransparency = 0.18
		highlight.Parent = adornment
		instances[highlight] = true
	end
	local scale = math.clamp(tonumber(options.Scale) or 1, 0.1, 1.8)
	local baseWidth = math.max(80, tonumber(options.Width) or 220)
	local baseHeight = math.max(28, tonumber(options.Height) or 52)
	local titleTextSize = math.max(8, tonumber(options.TitleTextSize) or 14)
	local detailTextSize = math.max(8, tonumber(options.DetailTextSize) or 12)
	local compact = options.Compact == true
	local horizontalPadding = compact and 10 or 14
	local titleY = compact and 3 or 5
	local detailY = compact and math.floor(baseHeight * 0.52) or 26
	local offset = typeof(options.Offset) == "Vector3" and options.Offset or Vector3.new(0, 2.5, 0)
	local sizeOffset = typeof(options.SizeOffset) == "Vector2" and options.SizeOffset or Vector2.zero
	local billboard = create("BillboardGui", {
		Name = "FrostScriptsLabel",
		Adornee = part,
		AlwaysOnTop = true,
		MaxDistance = tonumber(options.MaxDistance) or 750,
		Size = UDim2.fromOffset(baseWidth * scale, baseHeight * scale),
		StudsOffsetWorldSpace = offset,
		SizeOffset = sizeOffset,
		Parent = self.OverlayGui,
	})
	local panelStroke = stroke(color, 0.22)
	local panel = create("Frame", {
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = THEME.Background,
		BackgroundTransparency = 0.12,
		BorderSizePixel = 0,
		Parent = billboard,
	}, { corner(9), panelStroke })
	local titleLabel = create("TextLabel", {
		Position = UDim2.fromOffset(horizontalPadding * scale, titleY * scale),
		Size = UDim2.new(1, -horizontalPadding * 2 * scale, 0, (compact and 17 or 21) * scale),
		BackgroundTransparency = 1,
		Text = options.Title or "Marker",
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = titleTextSize * scale,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = panel,
	})
	local detailLabel = create("TextLabel", {
		Position = UDim2.fromOffset(horizontalPadding * scale, detailY * scale),
		Size = UDim2.new(1, -horizontalPadding * 2 * scale, 0, (compact and 14 or 18) * scale),
		BackgroundTransparency = 1,
		Text = options.Detail or "Marker",
		TextColor3 = color,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamMedium,
		TextSize = detailTextSize * scale,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = panel,
	})
	instances[billboard] = true
	local marker = {
		Billboard = billboard,
		Highlight = highlight,
	}
	local function applyGeometry()
		billboard.Size = UDim2.fromOffset(baseWidth * scale, baseHeight * scale)
		titleLabel.Position = UDim2.fromOffset(horizontalPadding * scale, titleY * scale)
		titleLabel.Size = UDim2.new(1, -horizontalPadding * 2 * scale, 0, (compact and 17 or 21) * scale)
		titleLabel.TextSize = titleTextSize * scale
		detailLabel.Position = UDim2.fromOffset(horizontalPadding * scale, detailY * scale)
		detailLabel.Size = UDim2.new(1, -horizontalPadding * 2 * scale, 0, (compact and 14 or 18) * scale)
		detailLabel.TextSize = detailTextSize * scale
	end
	function marker:Update(nextOptions)
		nextOptions = nextOptions or {}
		local nextColor = nextOptions.Color or color
		local nextScale = math.clamp(tonumber(nextOptions.Scale) or scale, 0.1, 1.8)
		titleLabel.Text = nextOptions.Title or titleLabel.Text
		detailLabel.Text = nextOptions.Detail or detailLabel.Text
		detailLabel.TextColor3 = nextColor
		panelStroke.Color = nextColor
		billboard.MaxDistance = tonumber(nextOptions.MaxDistance) or billboard.MaxDistance
		if typeof(nextOptions.Adornee) == "Instance" and nextOptions.Adornee:IsA("BasePart") then
			billboard.Adornee = nextOptions.Adornee
		end
		if typeof(nextOptions.Offset) == "Vector3" then
			billboard.StudsOffsetWorldSpace = nextOptions.Offset
		end
		if typeof(nextOptions.SizeOffset) == "Vector2" then
			billboard.SizeOffset = nextOptions.SizeOffset
		end
		if nextScale ~= scale then
			scale = nextScale
			applyGeometry()
		end
		if highlight then
			highlight.FillColor = nextColor
			highlight.OutlineColor = nextColor
		end
		color = nextColor
	end
	function marker:Destroy()
		if highlight then
			instances[highlight] = nil
			if highlight.Parent then highlight:Destroy() end
		end
		instances[billboard] = nil
		if billboard.Parent then billboard:Destroy() end
	end
	return marker
end

function Window:Destroy()
	if self._destroyed then return end
	self._destroyed = true
	self:CloseDropdown()
	for _, connection in ipairs(self._connections) do connection:Disconnect() end
	table.clear(self._connections)
	for _, running in pairs(self._tweens) do
		for _, animation in pairs(running) do animation:Cancel() end
	end
	table.clear(self._tweens)
	if self.Gui then self.Gui:Destroy() end
	if self.OverlayGui then self.OverlayGui:Destroy() end
	if self.NotificationGui then self.NotificationGui:Destroy() end
end

function Window:_applyTheme()
	for _, running in pairs(self._tweens) do
		for property, animation in pairs(running) do
			if property:find("Color") then animation:Cancel(); running[property] = nil end
		end
	end
	local function apply(root)
		if not root then return end
		local objects = root:GetDescendants()
		table.insert(objects, root)
		for _, object in ipairs(objects) do
			for attribute, themeKey in pairs(object:GetAttributes()) do
				local property = attribute:match("^FrostTheme_(.+)$")
				if property and THEME[themeKey] then
					pcall(function()
						object[property] = THEME[themeKey]
					end)
				end
			end
		end
	end
	apply(self.Gui)
	apply(self.OverlayGui)
	apply(self.NotificationGui)
	if self.ActiveTab then
		for _, item in ipairs(self.Tabs) do
			local selected = item == self.ActiveTab
			item.Button.BackgroundColor3 = selected and THEME.AccentSoft or THEME.Panel
			item.Label.TextColor3 = selected and THEME.Text or THEME.Muted
			item.IconLabel.TextColor3 = selected and THEME.Accent or THEME.Muted
			item.IconLabel.BackgroundColor3 = selected and THEME.AccentSoft or THEME.Surface
			item.Indicator.BackgroundColor3 = THEME.Accent
			item.Indicator.BackgroundTransparency = selected and 0 or 1
		end
	end
end

function Window:SetTheme(themeName)
	local source = THEMES[themeName]
	if not source then return false end
	self.ThemeName = themeName
	for key, value in pairs(source) do
		THEME[key] = value
	end
	self:_applyTheme()
	return true
end

function Window:SetThemeColor(key, color)
	if not THEME[key] or typeof(color) ~= "Color3" then return false end
	THEME[key] = color
	self.CustomTheme = true
	self:_applyTheme()
	return true
end

function Window:GetThemeColor(key)
	return THEME[key]
end

function Window:GetThemeNames()
	local names = {}
	for name in pairs(THEMES) do
		table.insert(names, name)
	end
	table.sort(names)
	return names
end

function Module:AddColorPicker(name, default, callback)
	self:_index(name)
	local value = typeof(default) == "Color3" and default or THEME.Accent
	local preview = self:_row(54)
	create("TextLabel", {
		Position = UDim2.fromOffset(16, 0),
		Size = UDim2.new(1, -96, 1, 0),
		BackgroundTransparency = 1,
		Text = name,
		TextColor3 = THEME.Text,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 14,
		Parent = preview,
	})
	local swatch = create("Frame", {
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -18, 0.5, 0),
		Size = UDim2.fromOffset(52, 30),
		BackgroundColor3 = value,
		BorderSizePixel = 0,
		Parent = preview,
	}, { corner(8), stroke(THEME.Border, 0.35) })
	local control = { Module = self, Value = value }
	local channels = {
		{ "R", function(color) return math.floor(color.R * 255 + 0.5) end },
		{ "G", function(color) return math.floor(color.G * 255 + 0.5) end },
		{ "B", function(color) return math.floor(color.B * 255 + 0.5) end },
	}
	local values = {
		R = channels[1][2](value),
		G = channels[2][2](value),
		B = channels[3][2](value),
	}
	local function refresh(silent)
		control.Value = Color3.fromRGB(values.R, values.G, values.B)
		swatch.BackgroundColor3 = control.Value
		if not silent then safeCall(control.Module.Window, callback, control.Value) end
	end
	local sliders = {}
	for _, channel in ipairs(channels) do
		sliders[channel[1]] = self:AddSlider(name .. " " .. channel[1], 0, 255, values[channel[1]], function(nextValue)
			values[channel[1]] = nextValue
			refresh(false)
		end, { Step = 1 })
	end
	function control:SetValue(color, silent)
		if typeof(color) ~= "Color3" then return end
		values.R = math.floor(color.R * 255 + 0.5)
		values.G = math.floor(color.G * 255 + 0.5)
		values.B = math.floor(color.B * 255 + 0.5)
		for channel, slider in pairs(sliders) do slider:SetValue(values[channel], true) end
		refresh(silent)
	end
	return control
end

function Window:AddClientSettings(tab, options)
	options = options or {}
	local state = options.State or {}
	local onChange = options.OnChange
	local appearance = tab:AddModule({
		Name = options.AppearanceName or "FrostScripts Appearance",
		Description = "Window, text, monitor, and animation settings",
		Collapsible = false,
	})
	appearance:AddToggle("Animations", state.Animations ~= false, function(value)
		state.Animations = value
		self:SetAnimations(value)
		if onChange then onChange("Animations", value) end
	end)
	appearance:AddDropdown("Window size", { "Comfortable", "Large", "Extra Large" }, state.SizePreset or self.SizePreset or "Large", function(value)
		state.SizePreset = value
		self:SetSizePreset(value)
		if onChange then onChange("SizePreset", value) end
	end)
	appearance:AddSlider("Text scale", 1, 1.3, state.TextScale or self.TextScale or 1, function(value)
		state.TextScale = value
		self:SetTextScale(value)
		if onChange then onChange("TextScale", value) end
	end, {
		Step = 0.05,
		Formatter = function(value) return string.format("%.2fx", value) end,
	})
	appearance:AddSlider("Background dim", 0, 75, state.DimAmount or self.DimAmount or 48, function(value)
		state.DimAmount = value
		self:SetDimAmount(value)
		if onChange then onChange("DimAmount", value) end
	end, {
		Step = 5,
		Formatter = function(value) return tostring(value) .. "%" end,
	})
	appearance:AddDropdown("Monitor side", { "Left", "Right" }, state.MonitorSide or self.MonitorSide or "Right", function(value)
		state.MonitorSide = value
		self:SetMonitorSide(value)
		if onChange then onChange("MonitorSide", value) end
	end)
	appearance:AddSlider("Monitor width", 320, 520, state.MonitorWidth or self.MonitorWidth or 380, function(value)
		state.MonitorWidth = value
		self:SetMonitorWidth(value)
		if onChange then onChange("MonitorWidth", value) end
	end, {
		Step = 20,
		Formatter = function(value) return tostring(value) .. " px" end,
	})

	local theme = tab:AddModule({
		Name = options.ThemeName or "FrostScripts Theme",
		Description = "Preset themes and color tuning",
		Collapsible = false,
	})
	theme:AddDropdown("Theme preset", self:GetThemeNames(), state.ThemeName or self.ThemeName or "Frost", function(value)
		state.ThemeName = value
		self:SetTheme(value)
		if onChange then onChange("ThemeName", value) end
	end)
	theme:AddColorPicker("Accent", THEME.Accent, function(color)
		self:SetThemeColor("Accent", color)
		if onChange then onChange("Accent", color) end
	end)
	theme:AddColorPicker("Success", THEME.Success, function(color)
		self:SetThemeColor("Success", color)
		if onChange then onChange("Success", color) end
	end)
	return appearance, theme
end

-- Composed with Library.lua by the build; shares its private UI helpers.
function Window:_targetWindowSize()
	local viewport = workspace.CurrentCamera and workspace.CurrentCamera.ViewportSize or Vector2.new(1280, 720)
	local scale = math.min(1, math.max(1, viewport.X - 24) / 480, math.max(1, viewport.Y - 24) / 460)
	local preset = SIZE_PRESETS[self.SizePreset] or SIZE_PRESETS.Large
	self.Scale.Scale = scale
	return Vector2.new(math.clamp((viewport.X - 24) / scale, 480, preset.X),
		math.clamp((viewport.Y - 24) / scale, 460, preset.Y))
end

function Window:_resizeWindow(animate)
	if self._destroyed then return end
	self:CloseDropdown()
	self.TargetSize = self:_targetWindowSize()
	local compact = self.TargetSize.X < 800
	local sidebarWidth = compact and 72 or 216
	self.Sidebar.Size = UDim2.new(0, sidebarWidth, 1, 0)
	self.Main.Position = UDim2.fromOffset(sidebarWidth, 0)
	self.Main.Size = UDim2.new(1, -sidebarWidth, 1, 0)
	self.BrandName.Visible = not compact
	self.BrandSubtitle.Visible = not compact
	self.NavCaption.Visible = not compact
	self.PlayerName.Visible = not compact
	self.Avatar.Position = UDim2.fromOffset(compact and 3 or 10, 10)
	self.Logo.Position = UDim2.fromOffset(compact and 14 or 20, 24)
	for _, tab in ipairs(self.Tabs) do
		tab.Label.Visible = not compact
		tab.IconLabel.Position = UDim2.fromOffset(compact and 9 or 14, 10)
	end
	self._compact = compact
	local size = UDim2.fromOffset(self.TargetSize.X, self.TargetSize.Y)
	if animate then self:_tween(self.Frame, 0.2, { Size = size }) else self.Frame.Size = size end
	self.Frame.Position = UDim2.fromScale(0.5, 0.5)
	self:_layoutMonitors()
	self:_layoutNotifications()
end

function Window:_refreshSearch()
	if self._destroyed or not self.ActiveTab then return end
	local tab = self.ActiveTab
	local query = (self.Search.Text or ""):lower()
	local shown, active = 0, 0
	for _, module in ipairs(tab.Modules) do
		local matches = not self.ActiveOnly or module.Enabled
		for word in query:gmatch("%S+") do
			if not module.SearchText:find(word, 1, true) then matches = false; break end
		end
		module.Card.Visible = matches
		if matches then shown += 1 end
		if module.Enabled then active += 1 end
	end
	self.Empty.Visible = shown == 0
	self.Empty.Text = #tab.Modules == 0 and "Your workspace is ready.\nAdd a module to get started."
		or "No matching modules\nTry a different search or turn off Active."
	self.Footer.Text = string.format("%d of %d modules  ·  %d active", shown, #tab.Modules, active)
end

function Window:SetSearch(query)
	self.Search.Text = tostring(query or "")
	self:_refreshSearch()
end

function Window:SetActiveOnly(enabled)
	self.ActiveOnly = enabled == true
	self:_tween(self.ActiveFilter, 0.12, {
		BackgroundColor3 = self.ActiveOnly and THEME.AccentSoft or THEME.PanelRaised,
		TextColor3 = self.ActiveOnly and THEME.Accent or THEME.Muted,
	})
	self:_refreshSearch()
end

function Window:CloseDropdown()
	if not self._dropdown then return end
	for _, connection in ipairs(self._dropdown.Connections) do connection:Disconnect() end
	self._dropdown.Root:Destroy()
	self._dropdown = nil
end

function Window:_openDropdown(control, name, options, anchor)
	if self._dropdown and self._dropdown.Control == control then self:CloseDropdown(); return end
	self:CloseDropdown()
	local root = create("Frame", { Size = UDim2.fromScale(1, 1), BackgroundTransparency = 1, ZIndex = 20, Parent = self.Gui })
	local connections = {}
	local function connect(signal, callback) table.insert(connections, signal:Connect(callback)) end
	self._dropdown = { Root = root, Control = control, Connections = connections }
	local scrim = create("TextButton", {
		Size = UDim2.fromScale(1, 1), Text = "", AutoButtonColor = false,
		BackgroundColor3 = Color3.new(0, 0, 0), BackgroundTransparency = 0.45, ZIndex = 20, Parent = root,
	})
	connect(scrim.Activated, function() self:CloseDropdown() end)
	local viewport = self.Gui.AbsoluteSize
	local width = math.min(360, math.max(180, viewport.X - 32))
	local height = math.min(360, math.max(140, viewport.Y - 32))
	local x = math.clamp(anchor.AbsolutePosition.X, 16, math.max(16, viewport.X - width - 16))
	local y = math.clamp(anchor.AbsolutePosition.Y, 16, math.max(16, viewport.Y - height - 16))
	local panel = create("Frame", {
		Position = UDim2.fromOffset(x, y), Size = UDim2.fromOffset(width, height),
		BackgroundColor3 = THEME.Panel, BorderSizePixel = 0, ZIndex = 21, Parent = root,
	}, { corner(14), stroke(THEME.Border, 0) })
	create("TextLabel", {
		Position = UDim2.fromOffset(16, 8), Size = UDim2.new(1, -70, 0, 32), Text = name,
		BackgroundTransparency = 1, TextColor3 = THEME.Text, Font = Enum.Font.GothamBold,
		TextSize = 14, TextXAlignment = Enum.TextXAlignment.Left, ZIndex = 22, Parent = panel,
	})
	local close = create("TextButton", {
		Position = UDim2.new(1, -48, 0, 0), Size = UDim2.fromOffset(44, 44), Text = "×",
		BackgroundTransparency = 1, TextColor3 = THEME.Muted, TextSize = 22, Font = Enum.Font.Gotham,
		ZIndex = 22, Parent = panel,
	})
	connect(close.Activated, function() self:CloseDropdown() end)
	local filter = create("TextBox", {
		Position = UDim2.fromOffset(12, 46), Size = UDim2.new(1, -24, 0, 40), Text = "",
		PlaceholderText = "Find an option…", ClearTextOnFocus = false,
		BackgroundColor3 = THEME.Surface, BorderSizePixel = 0, TextColor3 = THEME.Text,
		PlaceholderColor3 = THEME.Muted, TextSize = 13, Font = Enum.Font.Gotham,
		ZIndex = 22, Parent = panel,
	}, { corner(8) })
	local list = create("ScrollingFrame", {
		Position = UDim2.fromOffset(12, 94), Size = UDim2.new(1, -24, 1, -106),
		AutomaticCanvasSize = Enum.AutomaticSize.Y, CanvasSize = UDim2.new(),
		BackgroundTransparency = 1, BorderSizePixel = 0, ScrollBarThickness = 3,
		ScrollBarImageColor3 = THEME.Accent, ZIndex = 22, Parent = panel,
	}, { create("UIListLayout", { Padding = UDim.new(0, 4), SortOrder = Enum.SortOrder.LayoutOrder }) })
	local entries = {}
	for index, option in ipairs(options) do
		local label, value = optionParts(option)
		local selected = value == control.Value
		local button = create("TextButton", {
			Size = UDim2.new(1, -5, 0, 44), LayoutOrder = index,
			Text = (selected and "✓  " or "    ") .. label,
			TextColor3 = selected and THEME.Accent or THEME.Text, Font = Enum.Font.GothamMedium,
			TextSize = 13, TextXAlignment = Enum.TextXAlignment.Left,
			BackgroundColor3 = selected and THEME.AccentSoft or THEME.PanelRaised,
			BorderSizePixel = 0, AutoButtonColor = true, ZIndex = 23, Parent = list,
		}, { corner(8) })
		table.insert(entries, { Label = label:lower(), Button = button })
		connect(button.Activated, function() self:CloseDropdown(); control:SetValue(value) end)
	end
	connect(filter:GetPropertyChangedSignal("Text"), function()
		for _, entry in ipairs(entries) do entry.Button.Visible = entry.Label:find(filter.Text:lower(), 1, true) ~= nil end
	end)
end

function Library:CreateWindow(options)
	options = options or {}
	local player = Players.LocalPlayer
	local parent = player:WaitForChild("PlayerGui")
	pcall(function() if type(gethui) == "function" then parent = gethui() end end)
	local guiName = options.GuiName or "FrostScriptsUI"
	if self._windows and self._windows[guiName] then self._windows[guiName]:Destroy() end
	self._windows = self._windows or {}
	local overlayName = options.OverlayName or "FrostScriptsOverlays"
	for _, name in ipairs({ guiName, overlayName, overlayName .. "Notifications" }) do
		local existing = parent:FindFirstChild(name)
		if existing then existing:Destroy() end
	end
	local window = setmetatable({
		Animations = options.Animations ~= false, Visible = true,
		SizePreset = options.SizePreset or "Large", ThemeName = options.Theme or "Frost",
		TextScale = math.clamp(tonumber(options.TextScale) or 1, 1, 1.3),
		DimAmount = math.clamp(tonumber(options.DimAmount) or 40, 0, 75),
		MonitorWidth = math.clamp(tonumber(options.MonitorWidth) or 380, 320, 520),
		MonitorSide = options.MonitorSide == "Left" and "Left" or "Right",
		Tabs = {}, _tabsByName = {}, Keybinds = {}, Monitors = {}, Notifications = {},
		_monitorCount = 0, _connections = {}, _tweens = setmetatable({}, { __mode = "k" }),
		ActiveOnly = false, _visibilityToken = 0,
		ReservedKeys = options.ReservedKeys or {
			[Enum.KeyCode.W] = true, [Enum.KeyCode.A] = true, [Enum.KeyCode.S] = true,
			[Enum.KeyCode.D] = true, [Enum.KeyCode.Space] = true, [Enum.KeyCode.LeftControl] = true,
		},
	}, Window)
	self._windows[guiName] = window
	window.Gui = create("ScreenGui", {
		Name = guiName, ResetOnSpawn = false, IgnoreGuiInset = true,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling, DisplayOrder = 100, Parent = parent,
	})
	window.OverlayGui = create("ScreenGui", {
		Name = overlayName, ResetOnSpawn = false, IgnoreGuiInset = true,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling, DisplayOrder = 90, Parent = parent,
	})
	window.NotificationGui = create("ScreenGui", {
		Name = overlayName .. "Notifications", ResetOnSpawn = false, IgnoreGuiInset = true,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling, DisplayOrder = 102, Parent = parent,
	})
	window.Shade = create("Frame", {
		Name = "Shade", Size = UDim2.fromScale(1, 1), BackgroundColor3 = Color3.new(0, 0, 0),
		BackgroundTransparency = 1 - window.DimAmount / 100, BorderSizePixel = 0, Parent = window.Gui,
	})
	window.Frame = create("CanvasGroup", {
		Name = "FrostWorkspace", AnchorPoint = Vector2.new(0.5, 0.5), Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(1040, 650), BackgroundColor3 = THEME.Background,
		BorderSizePixel = 0, ClipsDescendants = true, Parent = window.Gui,
	}, { corner(18), stroke(THEME.Border, 0.12) })
	window.Scale = create("UIScale", { Parent = window.Frame })
	window.Sidebar = create("Frame", {
		Name = "Sidebar", Size = UDim2.new(0, 216, 1, 0), BackgroundColor3 = THEME.Panel,
		BorderSizePixel = 0, Parent = window.Frame,
	})
	create("Frame", { Position = UDim2.new(1, -1, 0, 0), Size = UDim2.new(0, 1, 1, 0),
		BackgroundColor3 = THEME.Border, BackgroundTransparency = 0.45, BorderSizePixel = 0, Parent = window.Sidebar })
	window.Logo = create("TextLabel", {
		Position = UDim2.fromOffset(20, 24), Size = UDim2.fromOffset(44, 44), Text = options.Logo or "F",
		BackgroundColor3 = THEME.AccentSoft, TextColor3 = THEME.Accent, Font = Enum.Font.GothamBold,
		TextSize = 26, BorderSizePixel = 0, Parent = window.Sidebar,
	}, { corner(13), stroke(THEME.Accent, 0.65) })
	local function label(parentObject, text, position, size, fontSize, color, bold)
		return create("TextLabel", { Text = text, Position = position, Size = size, BackgroundTransparency = 1,
			TextSize = fontSize, TextColor3 = color, Font = bold and Enum.Font.GothamBold or Enum.Font.GothamMedium,
			TextXAlignment = Enum.TextXAlignment.Left, Parent = parentObject })
	end
	window.BrandName = label(window.Sidebar, options.Name or "FrostScripts", UDim2.fromOffset(76, 24), UDim2.new(1, -84, 0, 24), 16, THEME.Text, true)
	window.BrandSubtitle = label(window.Sidebar, "YOUR GAME. YOUR WAY.", UDim2.fromOffset(76, 50), UDim2.new(1, -84, 0, 16), 8, THEME.Muted, true)
	window.NavCaption = label(window.Sidebar, "WORKSPACE", UDim2.fromOffset(24, 100), UDim2.new(1, -40, 0, 18), 10, THEME.Muted, true)
	window.Navigation = create("ScrollingFrame", {
		Name = "Navigation", Position = UDim2.fromOffset(12, 132), Size = UDim2.new(1, -24, 1, -228),
		BackgroundTransparency = 1, BorderSizePixel = 0, AutomaticCanvasSize = Enum.AutomaticSize.Y,
		CanvasSize = UDim2.new(), ScrollBarThickness = 0, Parent = window.Sidebar,
	}, { create("UIListLayout", { Padding = UDim.new(0, 6), SortOrder = Enum.SortOrder.LayoutOrder }) })
	local playerCard = create("Frame", {
		Position = UDim2.new(0, 12, 1, -78), Size = UDim2.new(1, -24, 0, 58),
		BackgroundColor3 = THEME.PanelRaised, BorderSizePixel = 0, Parent = window.Sidebar,
	}, { corner(12), stroke(THEME.Border, 0.55) })
	window.Avatar = label(playerCard, string.upper(player.Name:sub(1, 1)), UDim2.fromOffset(10, 10), UDim2.fromOffset(38, 38), 15, THEME.Accent, true)
	window.Avatar.BackgroundColor3 = THEME.AccentSoft
	window.Avatar.BackgroundTransparency = 0
	window.Avatar.TextXAlignment = Enum.TextXAlignment.Center
	corner(10).Parent = window.Avatar
	window.PlayerName = label(playerCard, player.DisplayName or player.Name, UDim2.fromOffset(60, 0), UDim2.new(1, -68, 1, 0), 12, THEME.Text, true)
	window.Main = create("Frame", { Name = "Main", BackgroundTransparency = 1, Parent = window.Frame })
	local topbar = create("Frame", { Name = "Header", Size = UDim2.new(1, 0, 0, 108), BackgroundTransparency = 1, Parent = window.Main })
	label(topbar, string.upper(options.Game or "FROSTSCRIPTS"), UDim2.fromOffset(24, 18), UDim2.new(1, -96, 0, 16), 10, THEME.Accent, true)
	window.PageTitle = label(topbar, "Workspace", UDim2.fromOffset(24, 39), UDim2.new(1, -96, 0, 32), 27, THEME.Text, true)
	window.PageSubtitle = label(topbar, "", UDim2.fromOffset(24, 77), UDim2.new(1, -48, 0, 19), 12, THEME.Muted, false)
	local close = create("TextButton", {
		Position = UDim2.new(1, -68, 0, 24), Size = UDim2.fromOffset(44, 44), Text = "−",
		BackgroundColor3 = THEME.PanelRaised, TextColor3 = THEME.Muted, BorderSizePixel = 0,
		Font = Enum.Font.Gotham, TextSize = 24, AutoButtonColor = false, Parent = topbar,
	}, { corner(12), stroke(THEME.Border, 0.5) })
	window:_hover(close, THEME.PanelRaised, THEME.SurfaceHover)
	window:_connect(close.Activated, function() window:SetVisible(false) end)
	local toolbar = create("Frame", { Position = UDim2.fromOffset(24, 114), Size = UDim2.new(1, -48, 0, 44), BackgroundTransparency = 1, Parent = window.Main })
	local searchFrame = create("Frame", { Size = UDim2.new(1, -92, 1, 0), BackgroundColor3 = THEME.PanelRaised, BorderSizePixel = 0, Parent = toolbar }, { corner(10), stroke(THEME.Border, 0.4) })
	window.Search = create("TextBox", {
		Position = UDim2.fromOffset(14, 0), Size = UDim2.new(1, -56, 1, 0), Text = "",
		PlaceholderText = "Search this tab…", ClearTextOnFocus = false,
		BackgroundTransparency = 1, TextColor3 = THEME.Text, PlaceholderColor3 = THEME.Muted,
		TextSize = 13, Font = Enum.Font.GothamMedium, TextXAlignment = Enum.TextXAlignment.Left, Parent = searchFrame,
	})
	local clear = create("TextButton", { Position = UDim2.new(1, -44, 0, 0), Size = UDim2.fromOffset(44, 44),
		Text = "×", TextSize = 18, Font = Enum.Font.Gotham, TextColor3 = THEME.Muted,
		BackgroundTransparency = 1, Parent = searchFrame })
	window:_connect(clear.Activated, function() window:SetSearch("") end)
	window:_connect(window.Search:GetPropertyChangedSignal("Text"), function() window:_refreshSearch() end)
	window.ActiveFilter = create("TextButton", { Position = UDim2.new(1, -82, 0, 0), Size = UDim2.fromOffset(82, 44),
		Text = "Active", TextSize = 12, Font = Enum.Font.GothamBold, TextColor3 = THEME.Muted,
		BackgroundColor3 = THEME.PanelRaised, AutoButtonColor = false, BorderSizePixel = 0, Parent = toolbar,
	}, { corner(10), stroke(THEME.Border, 0.4) })
	window:_connect(window.ActiveFilter.Activated, function() window:SetActiveOnly(not window.ActiveOnly) end)
	window.Content = create("Frame", { Position = UDim2.fromOffset(20, 174), Size = UDim2.new(1, -40, 1, -218),
		BackgroundTransparency = 1, ClipsDescendants = true, Parent = window.Main })
	window.Empty = label(window.Main, "", UDim2.new(0, 32, 0.5, 0), UDim2.new(1, -64, 0, 90), 14, THEME.Muted, false)
	window.Empty.TextXAlignment = Enum.TextXAlignment.Center
	window.Empty.Visible = false
	window.Footer = label(window.Main, "Ready", UDim2.new(0, 24, 1, -32), UDim2.new(1, -180, 0, 20), 11, THEME.Muted, false)
	label(window.Main, "CTRL K  /  SEARCH", UDim2.new(1, -152, 1, -32), UDim2.fromOffset(132, 20), 9, THEME.Muted, true)
	window.Launcher = create("TextButton", { Name = "ReopenFrostScripts", AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 20, 1, -20), Size = UDim2.fromOffset(52, 52), Text = "F",
		TextSize = 24, Font = Enum.Font.GothamBold, TextColor3 = THEME.Accent,
		BackgroundColor3 = THEME.Panel, BorderSizePixel = 0, Visible = false, Parent = window.OverlayGui,
	}, { corner(16), stroke(THEME.Accent, 0.25) })
	window:_connect(window.Launcher.Activated, function() window:SetVisible(true) end)
	window:_makeDraggable(window.Frame, topbar)
	window:_resizeWindow(false)
	local cameraConnection
	local function watchCamera()
		if cameraConnection then cameraConnection:Disconnect() end
		if workspace.CurrentCamera then
			cameraConnection = workspace.CurrentCamera:GetPropertyChangedSignal("ViewportSize"):Connect(function() window:_resizeWindow(false) end)
		end
		window:_resizeWindow(false)
	end
	window:_connect(workspace:GetPropertyChangedSignal("CurrentCamera"), watchCamera)
	window:_connect(window.Gui.Destroying, function() if cameraConnection then cameraConnection:Disconnect() end; window:Destroy() end)
	watchCamera()
	window:_connect(UserInputService.InputBegan, function(input, processed) window:_handleKeyboard(input, processed) end)
	window:SetTheme(options.Theme or "Frost")
	window.Frame.GroupTransparency = 1
	window:_tween(window.Frame, 0.22, { GroupTransparency = 0 })
	window:_applyTextScale()
	return window
end

function Library.new(options)
	return Library:CreateWindow(options)
end

Library.Theme = THEME
Library.Themes = THEMES

return Library
