local chunk = assert(loadstring(UI_SOURCE, "@FrostScripts/UI"))
setfenv(chunk, Mock.Env)
local UI = chunk()
local window = UI.new({ Animations = false })
local home = window:AddTab("Home", "H", "Overview")
local modules = window:AddTab("Modules", "M", "Features")
local alpha = modules:AddModule({ Name = "Flight", Description = "Movement", Toggleable = true })
local beta = modules:AddModule({ Name = "Harvest", Description = "Collect resources" })
local slider = alpha:AddSlider("Vertical speed", 5, 25, 5, function() end, { Step = 3 })
local dropdown = beta:AddDropdown("Priority", { "Nearest", "Farthest", "Largest" }, "Nearest", function() end)
local empty = beta:AddDropdown("Empty", {}, nil, function() end)
local chips = beta:AddMultiDropdown("Colors", { "Blue", "Red" }, { Blue = true }, function() end)
beta:AddNumberInput("Budget", 20, function() end, { Min = 1, Max = 100 })
beta:AddButton("Run", function() end)
beta:AddParagraph("Details", "Description")
beta:AddColorPicker("Accent", UI.Theme.Accent, function() end)
Mock.Flush()
local passed = 0
local function test(name, callback)
	local ok, err = pcall(callback)
	assert(ok, name .. ": " .. tostring(err))
	passed += 1; print("PASS " .. name)
end

test("tabs and controls construct without gameplay dependencies", function()
	assert(window.ActiveTab == home and #modules.Modules == 2)
	assert(empty.Value == nil and dropdown.Value == "Nearest")
	slider:SetValue(9, true)
	assert(slider.Value == 8, "slider step must be relative to minimum")
end)
test("search matches control names and supports active filtering", function()
	window:SelectTab(modules)
	window:SetSearch("vertical speed")
	assert(alpha.Card.Visible and not beta.Card.Visible)
	window:SetSearch("unmatched")
	assert(window.Empty.Visible and not alpha.Card.Visible)
	window:SetSearch("")
	alpha:SetEnabled(true)
	window:SetActiveOnly(true)
	assert(alpha.Card.Visible and not beta.Card.Visible)
	alpha:SetEnabled(false)
	assert(window.Empty.Visible)
	window:SetActiveOnly(false)
end)
test("phone and landscape viewports fit the window", function()
	for _, size in ipairs({ { 390, 844 }, { 844, 390 }, { 320, 568 }, { 1280, 800 } }) do
		Mock.Resize(size[1], size[2])
		assert(window.TargetSize.X * window.Scale.Scale <= size[1] - 23.9)
		assert(window.TargetSize.Y * window.Scale.Scale <= size[2] - 23.9)
	end
	Mock.Resize(390, 844)
	assert(window._compact and not modules.Label.Visible)
	local added = window:AddTab("Settings", "S", "Appearance")
	assert(not added.Label.Visible)
	Mock.Resize(1280, 800)
	assert(not window._compact and modules.Label.Visible)
end)
test("rapid hide and reopen ignores old delayed work", function()
	window:SetVisible(false)
	assert(window.Launcher.Visible)
	window:SetVisible(true)
	Mock.FlushDelayed()
	assert(window.Gui.Enabled and not window.Launcher.Visible)
end)
test("dropdown chooses arbitrary options and disconnects popup events", function()
	window:_openDropdown(dropdown, "Priority", { "Nearest", "Farthest", "Largest" }, beta.Card)
	local popup = window._dropdown
	for _, object in ipairs(popup.Root:GetDescendants()) do
		if object:IsA("TextButton") and object.Text:find("Largest", 1, true) then object.Activated:Fire(); break end
	end
	assert(dropdown.Value == "Largest" and window._dropdown == nil)
	for _, connection in ipairs(popup.Connections) do assert(not connection.Connected) end
end)
test("theme changes preserve selected chips and update hover colors", function()
	window:SetTheme("Rose")
	assert(chips.Buttons.Blue.BackgroundColor3 == UI.Theme.AccentSoft)
	chips:SetValue({ Red = true }, true)
	window:SetTheme("Frost")
	assert(chips.Buttons.Red.BackgroundColor3 == UI.Theme.AccentSoft)
	assert(chips.Buttons.Blue.BackgroundColor3 == UI.Theme.PanelRaised)
end)
test("notifications are bounded, dismissible, and fit narrow viewports", function()
	Mock.Resize(320, 568)
	for index = 1, 5 do window:Notify({ Text = "Message " .. index }) end
	assert(#window.Notifications == 3)
	local frame = window.Notifications[3]
	assert(frame.Size.X.Offset <= 288 and frame.Parent == window.NotificationGui)
	for _, object in ipairs(frame:GetChildren()) do
		if object:IsA("TextButton") then object.Activated:Fire(); break end
	end
	assert(#window.Notifications == 2)
	Mock.FlushDelayed(); Mock.FlushDelayed()
	assert(#window.Notifications == 0)
end)
test("destroy disconnects listeners and is safe to repeat", function()
	local connections = table.clone(window._connections)
	window:Destroy(); window:Destroy()
	Mock.Flush()
	assert(window.Gui.Parent == nil and window.OverlayGui.Parent == nil)
	for _, connection in ipairs(connections) do assert(not connection.Connected) end
end)
print(string.format("%d UI behavior tests passed (mock services, no visual rendering)", passed))
