"""Build deterministic loadstring entry points using only Python's standard library."""
from pathlib import Path
import argparse
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = "-- Generated by tools/build.py. Edit src/ instead.\n"


def outputs():
    api = [HEADER, 'local API = { Version = "2.0.0", TextData = { Shared = {} } }\n']
    for name, field in (("Scripts", "Catalog"), ("UI", "UIState")):
        source = (ROOT / f"config/{name}.lua").read_text(encoding="utf-8")
        api.append(f"API.{field} = (function()\n{source.rstrip()}\nend)()\n")
    text_factory = (ROOT / "src/shared/Text.lua").read_text(encoding="utf-8")
    api.append("local makeText = (function()\n" + text_factory + "\nend)()\n")
    for name in ("Loader", "Assets", "Copy", "Utilities", "Feature", "Universal"):
        source = (ROOT / f"src/api/{name}.lua").read_text(encoding="utf-8")
        api.append(f"\n-- {name}\ndo\n{source.rstrip()}\nend\n")
    api.append("\nreturn API\n")
    result = {"dist/api/FrostScriptsAPI.lua": "".join(api)}
    ui = (ROOT / "src/ui/Library.lua").read_text(encoding="utf-8")
    shell = (ROOT / "src/ui/Shell.lua").read_text(encoding="utf-8")
    for name in ("Themes", "Icons", "ThemeGallery", "Experience", "Cards"):
        source = (ROOT / f"src/ui/{name}.lua").read_text(encoding="utf-8")
        ui = ui.replace(f"-- @include {name}.lua", source.rstrip())
    defaults = (ROOT / "config/UI.lua").read_text(encoding="utf-8")
    text_prefix = "local UI_COPY = { Shared = {} }\nlocal makeText = (function()\n" + text_factory + "\nend)()\n"
    result["dist/ui/UI.lua"] = HEADER + text_prefix + "local UI_DEFAULTS = (function()\n" + defaults + "\nend)()\n" + ui.replace("-- @include Shell.lua", shell.rstrip())
    bootstrap = (ROOT / "src/loader/Bootstrap.lua").read_text(encoding="utf-8")
    result["dist/launchers/Loader.lua"] = HEADER + bootstrap
    result["dist/launcher/App.lua"] = HEADER + (ROOT / "src/launcher/App.lua").read_text(encoding="utf-8")
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated files are stale")
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_bytes() != content.encode("utf-8"):
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Stale generated files: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("Generated files are current." if args.check else "Built API, UI, and the single script-library launcher.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
