"""Build deterministic loadstring entry points using only Python's standard library."""
from pathlib import Path
import argparse
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = "-- Generated by tools/build.py. Edit src/ instead.\n"


def outputs():
    api = [HEADER, 'local API = { Version = "2.0.0" }\n']
    for name in ("Loader", "Utilities", "Feature", "Universal"):
        source = (ROOT / f"src/api/{name}.lua").read_text(encoding="utf-8")
        api.append(f"\n-- {name}\ndo\n{source.rstrip()}\nend\n")
    api.append("\nreturn API\n")
    result = {"FrostScriptsAPI.lua": "".join(api)}
    result["UI.lua"] = HEADER + (ROOT / "src/ui/Library.lua").read_text(encoding="utf-8")
    bootstrap = (ROOT / "src/loader/Bootstrap.lua").read_text(encoding="utf-8")
    for name in ("GrassCutter", "NeedleInHay"):
        result[f"{name}.lua"] = HEADER + bootstrap.replace("__GAME__", f'"{name}"')
    result["Loader.lua"] = HEADER + bootstrap.replace("__GAME__", 'config.Game or ""')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated files are stale")
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_bytes() != content.encode("utf-8"):
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Stale generated files: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("Generated files are current." if args.check else "Built API, UI, and three entry points.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
